/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaterialObject } from './MaterialObject';
import {
    MaterialObjectFromJSON,
    MaterialObjectFromJSONTyped,
    MaterialObjectToJSON,
    MaterialObjectToJSONTyped,
} from './MaterialObject';
import type { TextureObject } from './TextureObject';
import {
    TextureObjectFromJSON,
    TextureObjectFromJSONTyped,
    TextureObjectToJSON,
    TextureObjectToJSONTyped,
} from './TextureObject';

/**
 * 
 * @export
 * @interface AppearanceObject
 */
export interface AppearanceObject {
    /**
     * 
     * @type {Array<MaterialObject>}
     * @memberof AppearanceObject
     */
    materials?: Array<MaterialObject>;
    /**
     * 
     * @type {Array<TextureObject>}
     * @memberof AppearanceObject
     */
    textures?: Array<TextureObject>;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof AppearanceObject
     */
    vertices_texture?: Array<Array<number>>;
    /**
     * 
     * @type {string}
     * @memberof AppearanceObject
     */
    default_theme_texture?: string;
}

/**
 * Check if a given object implements the AppearanceObject interface.
 */
export function instanceOfAppearanceObject(value: object): value is AppearanceObject {
    return true;
}

export function AppearanceObjectFromJSON(json: any): AppearanceObject {
    return AppearanceObjectFromJSONTyped(json, false);
}

export function AppearanceObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppearanceObject {
    if (json == null) {
        return json;
    }
    return {
        
        'materials': json['materials'] == null ? undefined : ((json['materials'] as Array<any>).map(MaterialObjectFromJSON)),
        'textures': json['textures'] == null ? undefined : ((json['textures'] as Array<any>).map(TextureObjectFromJSON)),
        'vertices_texture': json['vertices-texture'] == null ? undefined : json['vertices-texture'],
        'default_theme_texture': json['default-theme-texture'] == null ? undefined : json['default-theme-texture'],
    };
}

export function AppearanceObjectToJSON(json: any): AppearanceObject {
    return AppearanceObjectToJSONTyped(json, false);
}

export function AppearanceObjectToJSONTyped(value?: AppearanceObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'materials': value['materials'] == null ? undefined : ((value['materials'] as Array<any>).map(MaterialObjectToJSON)),
        'textures': value['textures'] == null ? undefined : ((value['textures'] as Array<any>).map(TextureObjectToJSON)),
        'vertices-texture': value['vertices_texture'],
        'default-theme-texture': value['default_theme_texture'],
    };
}

