/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetType } from './AssetType';
import {
    AssetTypeFromJSON,
    AssetTypeFromJSONTyped,
    AssetTypeToJSON,
    AssetTypeToJSONTyped,
} from './AssetType';

/**
 * 
 * @export
 * @interface Asset
 */
export interface Asset {
    /**
     * 
     * @type {number}
     * @memberof Asset
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Asset
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Asset
     */
    file_name: string;
    /**
     * 
     * @type {AssetType}
     * @memberof Asset
     */
    file_type?: AssetType;
    /**
     * 
     * @type {string}
     * @memberof Asset
     */
    file_url: string;
    /**
     * 
     * @type {boolean}
     * @memberof Asset
     */
    downloaded: boolean;
    /**
     * 
     * @type {number}
     * @memberof Asset
     */
    feature_id: number;
    /**
     * 
     * @type {number}
     * @memberof Asset
     */
    layer_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Asset
     */
    interval_id: number | null;
}



/**
 * Check if a given object implements the Asset interface.
 */
export function instanceOfAsset(value: object): value is Asset {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('file_name' in value) || value['file_name'] === undefined) return false;
    if (!('file_url' in value) || value['file_url'] === undefined) return false;
    if (!('downloaded' in value) || value['downloaded'] === undefined) return false;
    if (!('feature_id' in value) || value['feature_id'] === undefined) return false;
    if (!('layer_id' in value) || value['layer_id'] === undefined) return false;
    if (!('interval_id' in value) || value['interval_id'] === undefined) return false;
    return true;
}

export function AssetFromJSON(json: any): Asset {
    return AssetFromJSONTyped(json, false);
}

export function AssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Asset {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'file_name': json['file_name'],
        'file_type': json['file_type'] == null ? undefined : AssetTypeFromJSON(json['file_type']),
        'file_url': json['file_url'],
        'downloaded': json['downloaded'],
        'feature_id': json['feature_id'],
        'layer_id': json['layer_id'],
        'interval_id': json['interval_id'],
    };
}

export function AssetToJSON(json: any): Asset {
    return AssetToJSONTyped(json, false);
}

export function AssetToJSONTyped(value?: Asset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'file_name': value['file_name'],
        'file_type': AssetTypeToJSON(value['file_type']),
        'file_url': value['file_url'],
        'downloaded': value['downloaded'],
        'feature_id': value['feature_id'],
        'layer_id': value['layer_id'],
        'interval_id': value['interval_id'],
    };
}

