/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttributeType
 */
export interface AttributeType {
    /**
     * 
     * @type {number}
     * @memberof AttributeType
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AttributeType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeType
     */
    alias: string;
    /**
     * 
     * @type {number}
     * @memberof AttributeType
     */
    unit_id: number | null;
}

/**
 * Check if a given object implements the AttributeType interface.
 */
export function instanceOfAttributeType(value: object): value is AttributeType {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('unit_id' in value) || value['unit_id'] === undefined) return false;
    return true;
}

export function AttributeTypeFromJSON(json: any): AttributeType {
    return AttributeTypeFromJSONTyped(json, false);
}

export function AttributeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'alias': json['alias'],
        'unit_id': json['unit_id'],
    };
}

export function AttributeTypeToJSON(json: any): AttributeType {
    return AttributeTypeToJSONTyped(json, false);
}

export function AttributeTypeToJSONTyped(value?: AttributeType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'alias': value['alias'],
        'unit_id': value['unit_id'],
    };
}

