/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeValueType } from './AttributeValueType';
import {
    AttributeValueTypeFromJSON,
    AttributeValueTypeFromJSONTyped,
    AttributeValueTypeToJSON,
    AttributeValueTypeToJSONTyped,
} from './AttributeValueType';

/**
 * 
 * @export
 * @interface Attribute
 */
export interface Attribute {
    /**
     * 
     * @type {number}
     * @memberof Attribute
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Attribute
     */
    value_string?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Attribute
     */
    value_integer?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Attribute
     */
    value_float?: number | null;
    /**
     * 
     * @type {AttributeValueType}
     * @memberof Attribute
     */
    value_type?: AttributeValueType;
    /**
     * 
     * @type {number}
     * @memberof Attribute
     */
    attribute_type_id: number;
    /**
     * 
     * @type {number}
     * @memberof Attribute
     */
    object_id: number;
    /**
     * 
     * @type {number}
     * @memberof Attribute
     */
    simulation_id: number | null;
}



/**
 * Check if a given object implements the Attribute interface.
 */
export function instanceOfAttribute(value: object): value is Attribute {
    if (!('attribute_type_id' in value) || value['attribute_type_id'] === undefined) return false;
    if (!('object_id' in value) || value['object_id'] === undefined) return false;
    if (!('simulation_id' in value) || value['simulation_id'] === undefined) return false;
    return true;
}

export function AttributeFromJSON(json: any): Attribute {
    return AttributeFromJSONTyped(json, false);
}

export function AttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attribute {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value_string': json['value_string'] == null ? undefined : json['value_string'],
        'value_integer': json['value_integer'] == null ? undefined : json['value_integer'],
        'value_float': json['value_float'] == null ? undefined : json['value_float'],
        'value_type': json['value_type'] == null ? undefined : AttributeValueTypeFromJSON(json['value_type']),
        'attribute_type_id': json['attribute_type_id'],
        'object_id': json['object_id'],
        'simulation_id': json['simulation_id'],
    };
}

export function AttributeToJSON(json: any): Attribute {
    return AttributeToJSONTyped(json, false);
}

export function AttributeToJSONTyped(value?: Attribute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'value_string': value['value_string'],
        'value_integer': value['value_integer'],
        'value_float': value['value_float'],
        'value_type': AttributeValueTypeToJSON(value['value_type']),
        'attribute_type_id': value['attribute_type_id'],
        'object_id': value['object_id'],
        'simulation_id': value['simulation_id'],
    };
}

