/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AttributeValueType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type AttributeValueType = typeof AttributeValueType[keyof typeof AttributeValueType];


export function instanceOfAttributeValueType(value: any): boolean {
    for (const key in AttributeValueType) {
        if (Object.prototype.hasOwnProperty.call(AttributeValueType, key)) {
            if (AttributeValueType[key as keyof typeof AttributeValueType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AttributeValueTypeFromJSON(json: any): AttributeValueType {
    return AttributeValueTypeFromJSONTyped(json, false);
}

export function AttributeValueTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeValueType {
    return json as AttributeValueType;
}

export function AttributeValueTypeToJSON(value?: AttributeValueType | null): any {
    return value as any;
}

export function AttributeValueTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AttributeValueType {
    return value as AttributeValueType;
}

