/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Building
 */
export interface Building {
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    object_id: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Building
     */
    geometry_processed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    egid_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    egrid_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    uuid_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    area_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    height_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    altitude_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    volume_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    num_floors_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    construction_period_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    building_type_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    sre_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    floor_height_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    area_person_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    habitable_surface_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    num_occupants_attribute_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    street_object_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    municipality_object_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    footprint_object_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    footprint_surface_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    regbl_object_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    land_plot_object_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    land_plot_surface_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    floor_surface_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    wall_surface_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    roof_surface_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    building_solid_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Building
     */
    roof_solid_id: number | null;
}

/**
 * Check if a given object implements the Building interface.
 */
export function instanceOfBuilding(value: object): value is Building {
    if (!('object_id' in value) || value['object_id'] === undefined) return false;
    if (!('egid_attribute_id' in value) || value['egid_attribute_id'] === undefined) return false;
    if (!('egrid_attribute_id' in value) || value['egrid_attribute_id'] === undefined) return false;
    if (!('uuid_attribute_id' in value) || value['uuid_attribute_id'] === undefined) return false;
    if (!('area_attribute_id' in value) || value['area_attribute_id'] === undefined) return false;
    if (!('height_attribute_id' in value) || value['height_attribute_id'] === undefined) return false;
    if (!('altitude_attribute_id' in value) || value['altitude_attribute_id'] === undefined) return false;
    if (!('volume_attribute_id' in value) || value['volume_attribute_id'] === undefined) return false;
    if (!('num_floors_attribute_id' in value) || value['num_floors_attribute_id'] === undefined) return false;
    if (!('construction_period_attribute_id' in value) || value['construction_period_attribute_id'] === undefined) return false;
    if (!('building_type_attribute_id' in value) || value['building_type_attribute_id'] === undefined) return false;
    if (!('sre_attribute_id' in value) || value['sre_attribute_id'] === undefined) return false;
    if (!('floor_height_attribute_id' in value) || value['floor_height_attribute_id'] === undefined) return false;
    if (!('area_person_attribute_id' in value) || value['area_person_attribute_id'] === undefined) return false;
    if (!('habitable_surface_attribute_id' in value) || value['habitable_surface_attribute_id'] === undefined) return false;
    if (!('num_occupants_attribute_id' in value) || value['num_occupants_attribute_id'] === undefined) return false;
    if (!('street_object_id' in value) || value['street_object_id'] === undefined) return false;
    if (!('municipality_object_id' in value) || value['municipality_object_id'] === undefined) return false;
    if (!('footprint_object_id' in value) || value['footprint_object_id'] === undefined) return false;
    if (!('footprint_surface_id' in value) || value['footprint_surface_id'] === undefined) return false;
    if (!('regbl_object_id' in value) || value['regbl_object_id'] === undefined) return false;
    if (!('land_plot_object_id' in value) || value['land_plot_object_id'] === undefined) return false;
    if (!('land_plot_surface_id' in value) || value['land_plot_surface_id'] === undefined) return false;
    if (!('floor_surface_id' in value) || value['floor_surface_id'] === undefined) return false;
    if (!('wall_surface_id' in value) || value['wall_surface_id'] === undefined) return false;
    if (!('roof_surface_id' in value) || value['roof_surface_id'] === undefined) return false;
    if (!('building_solid_id' in value) || value['building_solid_id'] === undefined) return false;
    if (!('roof_solid_id' in value) || value['roof_solid_id'] === undefined) return false;
    return true;
}

export function BuildingFromJSON(json: any): Building {
    return BuildingFromJSONTyped(json, false);
}

export function BuildingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Building {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'object_id': json['object_id'],
        'geometry_processed': json['geometry_processed'] == null ? undefined : json['geometry_processed'],
        'egid_attribute_id': json['egid_attribute_id'],
        'egrid_attribute_id': json['egrid_attribute_id'],
        'uuid_attribute_id': json['uuid_attribute_id'],
        'area_attribute_id': json['area_attribute_id'],
        'height_attribute_id': json['height_attribute_id'],
        'altitude_attribute_id': json['altitude_attribute_id'],
        'volume_attribute_id': json['volume_attribute_id'],
        'num_floors_attribute_id': json['num_floors_attribute_id'],
        'construction_period_attribute_id': json['construction_period_attribute_id'],
        'building_type_attribute_id': json['building_type_attribute_id'],
        'sre_attribute_id': json['sre_attribute_id'],
        'floor_height_attribute_id': json['floor_height_attribute_id'],
        'area_person_attribute_id': json['area_person_attribute_id'],
        'habitable_surface_attribute_id': json['habitable_surface_attribute_id'],
        'num_occupants_attribute_id': json['num_occupants_attribute_id'],
        'street_object_id': json['street_object_id'],
        'municipality_object_id': json['municipality_object_id'],
        'footprint_object_id': json['footprint_object_id'],
        'footprint_surface_id': json['footprint_surface_id'],
        'regbl_object_id': json['regbl_object_id'],
        'land_plot_object_id': json['land_plot_object_id'],
        'land_plot_surface_id': json['land_plot_surface_id'],
        'floor_surface_id': json['floor_surface_id'],
        'wall_surface_id': json['wall_surface_id'],
        'roof_surface_id': json['roof_surface_id'],
        'building_solid_id': json['building_solid_id'],
        'roof_solid_id': json['roof_solid_id'],
    };
}

export function BuildingToJSON(json: any): Building {
    return BuildingToJSONTyped(json, false);
}

export function BuildingToJSONTyped(value?: Building | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object_id': value['object_id'],
        'geometry_processed': value['geometry_processed'],
        'egid_attribute_id': value['egid_attribute_id'],
        'egrid_attribute_id': value['egrid_attribute_id'],
        'uuid_attribute_id': value['uuid_attribute_id'],
        'area_attribute_id': value['area_attribute_id'],
        'height_attribute_id': value['height_attribute_id'],
        'altitude_attribute_id': value['altitude_attribute_id'],
        'volume_attribute_id': value['volume_attribute_id'],
        'num_floors_attribute_id': value['num_floors_attribute_id'],
        'construction_period_attribute_id': value['construction_period_attribute_id'],
        'building_type_attribute_id': value['building_type_attribute_id'],
        'sre_attribute_id': value['sre_attribute_id'],
        'floor_height_attribute_id': value['floor_height_attribute_id'],
        'area_person_attribute_id': value['area_person_attribute_id'],
        'habitable_surface_attribute_id': value['habitable_surface_attribute_id'],
        'num_occupants_attribute_id': value['num_occupants_attribute_id'],
        'street_object_id': value['street_object_id'],
        'municipality_object_id': value['municipality_object_id'],
        'footprint_object_id': value['footprint_object_id'],
        'footprint_surface_id': value['footprint_surface_id'],
        'regbl_object_id': value['regbl_object_id'],
        'land_plot_object_id': value['land_plot_object_id'],
        'land_plot_surface_id': value['land_plot_surface_id'],
        'floor_surface_id': value['floor_surface_id'],
        'wall_surface_id': value['wall_surface_id'],
        'roof_surface_id': value['roof_surface_id'],
        'building_solid_id': value['building_solid_id'],
        'roof_solid_id': value['roof_solid_id'],
    };
}

