/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CityJSONSemanticObjectTypeStandard } from './CityJSONSemanticObjectTypeStandard';
import {
    CityJSONSemanticObjectTypeStandardFromJSON,
    CityJSONSemanticObjectTypeStandardFromJSONTyped,
    CityJSONSemanticObjectTypeStandardToJSON,
    CityJSONSemanticObjectTypeStandardToJSONTyped,
} from './CityJSONSemanticObjectTypeStandard';

/**
 * 
 * @export
 * @interface CityJSONSemanticObjectType
 */
export interface CityJSONSemanticObjectType {
}

/**
 * Check if a given object implements the CityJSONSemanticObjectType interface.
 */
export function instanceOfCityJSONSemanticObjectType(value: object): value is CityJSONSemanticObjectType {
    return true;
}

export function CityJSONSemanticObjectTypeFromJSON(json: any): CityJSONSemanticObjectType {
    return CityJSONSemanticObjectTypeFromJSONTyped(json, false);
}

export function CityJSONSemanticObjectTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONSemanticObjectType {
    return json;
}

export function CityJSONSemanticObjectTypeToJSON(json: any): CityJSONSemanticObjectType {
    return CityJSONSemanticObjectTypeToJSONTyped(json, false);
}

export function CityJSONSemanticObjectTypeToJSONTyped(value?: CityJSONSemanticObjectType | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

