/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CityJSONSemanticSurface } from './CityJSONSemanticSurface';
import {
    CityJSONSemanticSurfaceFromJSON,
    CityJSONSemanticSurfaceFromJSONTyped,
    CityJSONSemanticSurfaceToJSON,
    CityJSONSemanticSurfaceToJSONTyped,
} from './CityJSONSemanticSurface';

/**
 * 
 * @export
 * @interface CityJSONSemantics
 */
export interface CityJSONSemantics {
    /**
     * 
     * @type {Array<number | null>}
     * @memberof CityJSONSemantics
     */
    values: Array<number | null>;
    /**
     * 
     * @type {Array<CityJSONSemanticSurface>}
     * @memberof CityJSONSemantics
     */
    surfaces: Array<CityJSONSemanticSurface>;
}

/**
 * Check if a given object implements the CityJSONSemantics interface.
 */
export function instanceOfCityJSONSemantics(value: object): value is CityJSONSemantics {
    if (!('values' in value) || value['values'] === undefined) return false;
    if (!('surfaces' in value) || value['surfaces'] === undefined) return false;
    return true;
}

export function CityJSONSemanticsFromJSON(json: any): CityJSONSemantics {
    return CityJSONSemanticsFromJSONTyped(json, false);
}

export function CityJSONSemanticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONSemantics {
    if (json == null) {
        return json;
    }
    return {
        
        'values': json['values'],
        'surfaces': ((json['surfaces'] as Array<any>).map(CityJSONSemanticSurfaceFromJSON)),
    };
}

export function CityJSONSemanticsToJSON(json: any): CityJSONSemantics {
    return CityJSONSemanticsToJSONTyped(json, false);
}

export function CityJSONSemanticsToJSONTyped(value?: CityJSONSemantics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': value['values'],
        'surfaces': ((value['surfaces'] as Array<any>).map(CityJSONSemanticSurfaceToJSON)),
    };
}

