/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CityJSONGeometryObjectTexture
 */
export interface CityJSONGeometryObjectTexture {
}

/**
 * Check if a given object implements the CityJSONGeometryObjectTexture interface.
 */
export function instanceOfCityJSONGeometryObjectTexture(value: object): value is CityJSONGeometryObjectTexture {
    return true;
}

export function CityJSONGeometryObjectTextureFromJSON(json: any): CityJSONGeometryObjectTexture {
    return CityJSONGeometryObjectTextureFromJSONTyped(json, false);
}

export function CityJSONGeometryObjectTextureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONGeometryObjectTexture {
    return json;
}

export function CityJSONGeometryObjectTextureToJSON(json: any): CityJSONGeometryObjectTexture {
    return CityJSONGeometryObjectTextureToJSONTyped(json, false);
}

export function CityJSONGeometryObjectTextureToJSONTyped(value?: CityJSONGeometryObjectTexture | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

