/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CityJSONCityObjectTypeStandard = {
    building: 'Building',
    building_part: 'BuildingPart',
    building_room: 'BuildingRoom',
    building_storey: 'BuildingStorey',
    building_unit: 'BuildingUnit',
    building_installation: 'BuildingInstallation',
    water_body: 'WaterBody',
    road: 'Road',
    railway: 'Railway',
    transport_square: 'TransportSquare',
    tin_relief: 'TINRelief'
} as const;
export type CityJSONCityObjectTypeStandard = typeof CityJSONCityObjectTypeStandard[keyof typeof CityJSONCityObjectTypeStandard];


export function instanceOfCityJSONCityObjectTypeStandard(value: any): boolean {
    for (const key in CityJSONCityObjectTypeStandard) {
        if (Object.prototype.hasOwnProperty.call(CityJSONCityObjectTypeStandard, key)) {
            if (CityJSONCityObjectTypeStandard[key as keyof typeof CityJSONCityObjectTypeStandard] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CityJSONCityObjectTypeStandardFromJSON(json: any): CityJSONCityObjectTypeStandard {
    return CityJSONCityObjectTypeStandardFromJSONTyped(json, false);
}

export function CityJSONCityObjectTypeStandardFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONCityObjectTypeStandard {
    return json as CityJSONCityObjectTypeStandard;
}

export function CityJSONCityObjectTypeStandardToJSON(value?: CityJSONCityObjectTypeStandard | null): any {
    return value as any;
}

export function CityJSONCityObjectTypeStandardToJSONTyped(value: any, ignoreDiscriminator: boolean): CityJSONCityObjectTypeStandard {
    return value as CityJSONCityObjectTypeStandard;
}

