/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppearanceObject } from './AppearanceObject';
import {
    AppearanceObjectFromJSON,
    AppearanceObjectFromJSONTyped,
    AppearanceObjectToJSON,
    AppearanceObjectToJSONTyped,
} from './AppearanceObject';
import type { CityObject } from './CityObject';
import {
    CityObjectFromJSON,
    CityObjectFromJSONTyped,
    CityObjectToJSON,
    CityObjectToJSONTyped,
} from './CityObject';

/**
 * 
 * @export
 * @interface CityFeature
 */
export interface CityFeature {
    /**
     * 
     * @type {string}
     * @memberof CityFeature
     */
    type?: CityFeatureTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CityFeature
     */
    id: string;
    /**
     * 
     * @type {{ [key: string]: CityObject; }}
     * @memberof CityFeature
     */
    city_objects?: { [key: string]: CityObject; };
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof CityFeature
     */
    vertices?: Array<Array<number>>;
    /**
     * 
     * @type {AppearanceObject}
     * @memberof CityFeature
     */
    appearance?: AppearanceObject | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CityFeature
     */
    unit_of_measurement?: { [key: string]: string; } | null;
}


/**
 * @export
 */
export const CityFeatureTypeEnum = {
    city_json_feature: 'CityJSONFeature'
} as const;
export type CityFeatureTypeEnum = typeof CityFeatureTypeEnum[keyof typeof CityFeatureTypeEnum];


/**
 * Check if a given object implements the CityFeature interface.
 */
export function instanceOfCityFeature(value: object): value is CityFeature {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CityFeatureFromJSON(json: any): CityFeature {
    return CityFeatureFromJSONTyped(json, false);
}

export function CityFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityFeature {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'],
        'city_objects': json['CityObjects'] == null ? undefined : (mapValues(json['CityObjects'], CityObjectFromJSON)),
        'vertices': json['vertices'] == null ? undefined : json['vertices'],
        'appearance': json['appearance'] == null ? undefined : AppearanceObjectFromJSON(json['appearance']),
        'unit_of_measurement': json['+unitOfMeasurement'] == null ? undefined : json['+unitOfMeasurement'],
    };
}

export function CityFeatureToJSON(json: any): CityFeature {
    return CityFeatureToJSONTyped(json, false);
}

export function CityFeatureToJSONTyped(value?: CityFeature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'CityObjects': value['city_objects'] == null ? undefined : (mapValues(value['city_objects'], CityObjectToJSON)),
        'vertices': value['vertices'],
        'appearance': AppearanceObjectToJSON(value['appearance']),
        '+unitOfMeasurement': value['unit_of_measurement'],
    };
}

