/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CityJSONBoundariesTexture } from './CityJSONBoundariesTexture';
import {
    CityJSONBoundariesTextureFromJSON,
    CityJSONBoundariesTextureFromJSONTyped,
    CityJSONBoundariesTextureToJSON,
    CityJSONBoundariesTextureToJSONTyped,
} from './CityJSONBoundariesTexture';

/**
 * 
 * @export
 * @interface CityJSONGeometryObjectTextureTheme
 */
export interface CityJSONGeometryObjectTextureTheme {
    /**
     * 
     * @type {CityJSONBoundariesTexture}
     * @memberof CityJSONGeometryObjectTextureTheme
     */
    values: CityJSONBoundariesTexture;
}

/**
 * Check if a given object implements the CityJSONGeometryObjectTextureTheme interface.
 */
export function instanceOfCityJSONGeometryObjectTextureTheme(value: object): value is CityJSONGeometryObjectTextureTheme {
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function CityJSONGeometryObjectTextureThemeFromJSON(json: any): CityJSONGeometryObjectTextureTheme {
    return CityJSONGeometryObjectTextureThemeFromJSONTyped(json, false);
}

export function CityJSONGeometryObjectTextureThemeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONGeometryObjectTextureTheme {
    if (json == null) {
        return json;
    }
    return {
        
        'values': CityJSONBoundariesTextureFromJSON(json['values']),
    };
}

export function CityJSONGeometryObjectTextureThemeToJSON(json: any): CityJSONGeometryObjectTextureTheme {
    return CityJSONGeometryObjectTextureThemeToJSONTyped(json, false);
}

export function CityJSONGeometryObjectTextureThemeToJSONTyped(value?: CityJSONGeometryObjectTextureTheme | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': CityJSONBoundariesTextureToJSON(value['values']),
    };
}

