/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CityJSONSemanticObjectTypeStandard = {
    roof_surface: 'RoofSurface',
    ground_surface: 'GroundSurface',
    wall_surface: 'WallSurface',
    closure_surface: 'ClosureSurface',
    outer_ceiling_surface: 'OuterCeilingSurface',
    outer_floor_surface: 'OuterFloorSurface',
    window: 'Window',
    door: 'Door',
    interior_wall_surface: 'InteriorWallSurface',
    ceiling_surface: 'CeilingSurface',
    floor_surface: 'FloorSurface',
    water_surface: 'WaterSurface',
    water_ground_surface: 'WaterGroundSurface',
    water_closure_surface: 'WaterClosureSurface',
    traffic_area: 'TrafficArea',
    auxiliary_traffic_area: 'AuxiliaryTrafficArea',
    transportation_marking: 'TransportationMarking',
    transportation_hole: 'TransportationHole',
    vegetation_surface: 'VegetationSurface'
} as const;
export type CityJSONSemanticObjectTypeStandard = typeof CityJSONSemanticObjectTypeStandard[keyof typeof CityJSONSemanticObjectTypeStandard];


export function instanceOfCityJSONSemanticObjectTypeStandard(value: any): boolean {
    for (const key in CityJSONSemanticObjectTypeStandard) {
        if (Object.prototype.hasOwnProperty.call(CityJSONSemanticObjectTypeStandard, key)) {
            if (CityJSONSemanticObjectTypeStandard[key as keyof typeof CityJSONSemanticObjectTypeStandard] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CityJSONSemanticObjectTypeStandardFromJSON(json: any): CityJSONSemanticObjectTypeStandard {
    return CityJSONSemanticObjectTypeStandardFromJSONTyped(json, false);
}

export function CityJSONSemanticObjectTypeStandardFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONSemanticObjectTypeStandard {
    return json as CityJSONSemanticObjectTypeStandard;
}

export function CityJSONSemanticObjectTypeStandardToJSON(value?: CityJSONSemanticObjectTypeStandard | null): any {
    return value as any;
}

export function CityJSONSemanticObjectTypeStandardToJSONTyped(value: any, ignoreDiscriminator: boolean): CityJSONSemanticObjectTypeStandard {
    return value as CityJSONSemanticObjectTypeStandard;
}

