/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CityJSONGeometryBoundaries
 */
export interface CityJSONGeometryBoundaries {
}

/**
 * Check if a given object implements the CityJSONGeometryBoundaries interface.
 */
export function instanceOfCityJSONGeometryBoundaries(value: object): value is CityJSONGeometryBoundaries {
    return true;
}

export function CityJSONGeometryBoundariesFromJSON(json: any): CityJSONGeometryBoundaries {
    return CityJSONGeometryBoundariesFromJSONTyped(json, false);
}

export function CityJSONGeometryBoundariesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONGeometryBoundaries {
    return json;
}

export function CityJSONGeometryBoundariesToJSON(json: any): CityJSONGeometryBoundaries {
    return CityJSONGeometryBoundariesToJSONTyped(json, false);
}

export function CityJSONGeometryBoundariesToJSONTyped(value?: CityJSONGeometryBoundaries | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

