/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CityJSONBoundariesTexture
 */
export interface CityJSONBoundariesTexture {
}

/**
 * Check if a given object implements the CityJSONBoundariesTexture interface.
 */
export function instanceOfCityJSONBoundariesTexture(value: object): value is CityJSONBoundariesTexture {
    return true;
}

export function CityJSONBoundariesTextureFromJSON(json: any): CityJSONBoundariesTexture {
    return CityJSONBoundariesTextureFromJSONTyped(json, false);
}

export function CityJSONBoundariesTextureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONBoundariesTexture {
    return json;
}

export function CityJSONBoundariesTextureToJSON(json: any): CityJSONBoundariesTexture {
    return CityJSONBoundariesTextureToJSONTyped(json, false);
}

export function CityJSONBoundariesTextureToJSONTyped(value?: CityJSONBoundariesTexture | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

