/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CityJSONBoundariesMaterial
 */
export interface CityJSONBoundariesMaterial {
}

/**
 * Check if a given object implements the CityJSONBoundariesMaterial interface.
 */
export function instanceOfCityJSONBoundariesMaterial(value: object): value is CityJSONBoundariesMaterial {
    return true;
}

export function CityJSONBoundariesMaterialFromJSON(json: any): CityJSONBoundariesMaterial {
    return CityJSONBoundariesMaterialFromJSONTyped(json, false);
}

export function CityJSONBoundariesMaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONBoundariesMaterial {
    return json;
}

export function CityJSONBoundariesMaterialToJSON(json: any): CityJSONBoundariesMaterial {
    return CityJSONBoundariesMaterialToJSONTyped(json, false);
}

export function CityJSONBoundariesMaterialToJSONTyped(value?: CityJSONBoundariesMaterial | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

