/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CityJSONSemanticObjectType } from './CityJSONSemanticObjectType';
import {
    CityJSONSemanticObjectTypeFromJSON,
    CityJSONSemanticObjectTypeFromJSONTyped,
    CityJSONSemanticObjectTypeToJSON,
    CityJSONSemanticObjectTypeToJSONTyped,
} from './CityJSONSemanticObjectType';

/**
 * 
 * @export
 * @interface CityJSONSemanticSurface
 */
export interface CityJSONSemanticSurface {
    /**
     * 
     * @type {CityJSONSemanticObjectType}
     * @memberof CityJSONSemanticSurface
     */
    type: CityJSONSemanticObjectType;
}

/**
 * Check if a given object implements the CityJSONSemanticSurface interface.
 */
export function instanceOfCityJSONSemanticSurface(value: object): value is CityJSONSemanticSurface {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CityJSONSemanticSurfaceFromJSON(json: any): CityJSONSemanticSurface {
    return CityJSONSemanticSurfaceFromJSONTyped(json, false);
}

export function CityJSONSemanticSurfaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONSemanticSurface {
    if (json == null) {
        return json;
    }
    return {
        
        'type': CityJSONSemanticObjectTypeFromJSON(json['type']),
    };
}

export function CityJSONSemanticSurfaceToJSON(json: any): CityJSONSemanticSurface {
    return CityJSONSemanticSurfaceToJSONTyped(json, false);
}

export function CityJSONSemanticSurfaceToJSONTyped(value?: CityJSONSemanticSurface | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': CityJSONSemanticObjectTypeToJSON(value['type']),
    };
}

