/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSeriesInfo } from './TimeSeriesInfo';
import {
    TimeSeriesInfoFromJSON,
    TimeSeriesInfoFromJSONTyped,
    TimeSeriesInfoToJSON,
    TimeSeriesInfoToJSONTyped,
} from './TimeSeriesInfo';
import type { GeometryObject } from './GeometryObject';
import {
    GeometryObjectFromJSON,
    GeometryObjectFromJSONTyped,
    GeometryObjectToJSON,
    GeometryObjectToJSONTyped,
} from './GeometryObject';
import type { CityJSONCityObjectType } from './CityJSONCityObjectType';
import {
    CityJSONCityObjectTypeFromJSON,
    CityJSONCityObjectTypeFromJSONTyped,
    CityJSONCityObjectTypeToJSON,
    CityJSONCityObjectTypeToJSONTyped,
} from './CityJSONCityObjectType';

/**
 * 
 * @export
 * @interface CityObject
 */
export interface CityObject {
    /**
     * 
     * @type {CityJSONCityObjectType}
     * @memberof CityObject
     */
    type: CityJSONCityObjectType;
    /**
     * 
     * @type {Array<GeometryObject>}
     * @memberof CityObject
     */
    geometry: Array<GeometryObject>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CityObject
     */
    attributes?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: TimeSeriesInfo; }}
     * @memberof CityObject
     */
    time_series?: { [key: string]: TimeSeriesInfo; } | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CityObject
     */
    parents?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CityObject
     */
    children?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof CityObject
     */
    object_id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CityObject
     */
    layer?: string | null;
}

/**
 * Check if a given object implements the CityObject interface.
 */
export function instanceOfCityObject(value: object): value is CityObject {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('geometry' in value) || value['geometry'] === undefined) return false;
    return true;
}

export function CityObjectFromJSON(json: any): CityObject {
    return CityObjectFromJSONTyped(json, false);
}

export function CityObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityObject {
    if (json == null) {
        return json;
    }
    return {
        
        'type': CityJSONCityObjectTypeFromJSON(json['type']),
        'geometry': ((json['geometry'] as Array<any>).map(GeometryObjectFromJSON)),
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'time_series': json['time_series'] == null ? undefined : (mapValues(json['time_series'], TimeSeriesInfoFromJSON)),
        'parents': json['parents'] == null ? undefined : json['parents'],
        'children': json['children'] == null ? undefined : json['children'],
        'object_id': json['object_id'] == null ? undefined : json['object_id'],
        'layer': json['+layer'] == null ? undefined : json['+layer'],
    };
}

export function CityObjectToJSON(json: any): CityObject {
    return CityObjectToJSONTyped(json, false);
}

export function CityObjectToJSONTyped(value?: CityObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': CityJSONCityObjectTypeToJSON(value['type']),
        'geometry': ((value['geometry'] as Array<any>).map(GeometryObjectToJSON)),
        'attributes': value['attributes'],
        'time_series': value['time_series'] == null ? undefined : (mapValues(value['time_series'], TimeSeriesInfoToJSON)),
        'parents': value['parents'],
        'children': value['children'],
        'object_id': value['object_id'],
        '+layer': value['layer'],
    };
}

