/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CityJSONCityObjectTypeStandard } from './CityJSONCityObjectTypeStandard';
import {
    CityJSONCityObjectTypeStandardFromJSON,
    CityJSONCityObjectTypeStandardFromJSONTyped,
    CityJSONCityObjectTypeStandardToJSON,
    CityJSONCityObjectTypeStandardToJSONTyped,
} from './CityJSONCityObjectTypeStandard';

/**
 * 
 * @export
 * @interface CityJSONCityObjectType
 */
export interface CityJSONCityObjectType {
}

/**
 * Check if a given object implements the CityJSONCityObjectType interface.
 */
export function instanceOfCityJSONCityObjectType(value: object): value is CityJSONCityObjectType {
    return true;
}

export function CityJSONCityObjectTypeFromJSON(json: any): CityJSONCityObjectType {
    return CityJSONCityObjectTypeFromJSONTyped(json, false);
}

export function CityJSONCityObjectTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONCityObjectType {
    return json;
}

export function CityJSONCityObjectTypeToJSON(json: any): CityJSONCityObjectType {
    return CityJSONCityObjectTypeToJSONTyped(json, false);
}

export function CityJSONCityObjectTypeToJSONTyped(value?: CityJSONCityObjectType | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

