/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CityJSONGeometryLevelOfDetail = {
    _0: '0',
    _0_0: '0.0',
    _0_1: '0.1',
    _0_2: '0.2',
    _0_3: '0.3',
    _1: '1',
    _1_0: '1.0',
    _1_1: '1.1',
    _1_2: '1.2',
    _1_3: '1.3',
    _2: '2',
    _2_0: '2.0',
    _2_1: '2.1',
    _2_2: '2.2',
    _2_3: '2.3',
    _3: '3',
    _3_0: '3.0',
    _3_1: '3.1',
    _3_2: '3.2',
    _3_3: '3.3'
} as const;
export type CityJSONGeometryLevelOfDetail = typeof CityJSONGeometryLevelOfDetail[keyof typeof CityJSONGeometryLevelOfDetail];


export function instanceOfCityJSONGeometryLevelOfDetail(value: any): boolean {
    for (const key in CityJSONGeometryLevelOfDetail) {
        if (Object.prototype.hasOwnProperty.call(CityJSONGeometryLevelOfDetail, key)) {
            if (CityJSONGeometryLevelOfDetail[key as keyof typeof CityJSONGeometryLevelOfDetail] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CityJSONGeometryLevelOfDetailFromJSON(json: any): CityJSONGeometryLevelOfDetail {
    return CityJSONGeometryLevelOfDetailFromJSONTyped(json, false);
}

export function CityJSONGeometryLevelOfDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONGeometryLevelOfDetail {
    return json as CityJSONGeometryLevelOfDetail;
}

export function CityJSONGeometryLevelOfDetailToJSON(value?: CityJSONGeometryLevelOfDetail | null): any {
    return value as any;
}

export function CityJSONGeometryLevelOfDetailToJSONTyped(value: any, ignoreDiscriminator: boolean): CityJSONGeometryLevelOfDetail {
    return value as CityJSONGeometryLevelOfDetail;
}

