/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppearanceObject } from './AppearanceObject';
import {
    AppearanceObjectFromJSON,
    AppearanceObjectFromJSONTyped,
    AppearanceObjectToJSON,
    AppearanceObjectToJSONTyped,
} from './AppearanceObject';
import type { CityObject } from './CityObject';
import {
    CityObjectFromJSON,
    CityObjectFromJSONTyped,
    CityObjectToJSON,
    CityObjectToJSONTyped,
} from './CityObject';
import type { GeometryTemplates } from './GeometryTemplates';
import {
    GeometryTemplatesFromJSON,
    GeometryTemplatesFromJSONTyped,
    GeometryTemplatesToJSON,
    GeometryTemplatesToJSONTyped,
} from './GeometryTemplates';
import type { SimulationInfo } from './SimulationInfo';
import {
    SimulationInfoFromJSON,
    SimulationInfoFromJSONTyped,
    SimulationInfoToJSON,
    SimulationInfoToJSONTyped,
} from './SimulationInfo';

/**
 * 
 * @export
 * @interface CityModel
 */
export interface CityModel {
    /**
     * 
     * @type {string}
     * @memberof CityModel
     */
    type?: CityModelTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CityModel
     */
    version?: CityModelVersionEnum;
    /**
     * 
     * @type {{ [key: string]: CityObject; }}
     * @memberof CityModel
     */
    city_objects?: { [key: string]: CityObject; };
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof CityModel
     */
    vertices?: Array<Array<number>>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CityModel
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: Array<number>; }}
     * @memberof CityModel
     */
    transform?: { [key: string]: Array<number>; };
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof CityModel
     */
    extensions?: { [key: string]: { [key: string]: string; }; };
    /**
     * 
     * @type {AppearanceObject}
     * @memberof CityModel
     */
    appearance?: AppearanceObject | null;
    /**
     * 
     * @type {GeometryTemplates}
     * @memberof CityModel
     */
    geometry_templates?: GeometryTemplates | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CityModel
     */
    unit_of_measurement?: { [key: string]: string; } | null;
    /**
     * 
     * @type {Array<SimulationInfo>}
     * @memberof CityModel
     */
    simulations?: Array<SimulationInfo> | null;
    /**
     * 
     * @type {number}
     * @memberof CityModel
     */
    num_objects?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CityModel
     */
    num_surfaces?: number | null;
}


/**
 * @export
 */
export const CityModelTypeEnum = {
    city_json: 'CityJSON'
} as const;
export type CityModelTypeEnum = typeof CityModelTypeEnum[keyof typeof CityModelTypeEnum];

/**
 * @export
 */
export const CityModelVersionEnum = {
    _2_0: '2.0'
} as const;
export type CityModelVersionEnum = typeof CityModelVersionEnum[keyof typeof CityModelVersionEnum];


/**
 * Check if a given object implements the CityModel interface.
 */
export function instanceOfCityModel(value: object): value is CityModel {
    return true;
}

export function CityModelFromJSON(json: any): CityModel {
    return CityModelFromJSONTyped(json, false);
}

export function CityModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityModel {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'version': json['version'] == null ? undefined : json['version'],
        'city_objects': json['CityObjects'] == null ? undefined : (mapValues(json['CityObjects'], CityObjectFromJSON)),
        'vertices': json['vertices'] == null ? undefined : json['vertices'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'transform': json['transform'] == null ? undefined : json['transform'],
        'extensions': json['extensions'] == null ? undefined : json['extensions'],
        'appearance': json['appearance'] == null ? undefined : AppearanceObjectFromJSON(json['appearance']),
        'geometry_templates': json['geometry-templates'] == null ? undefined : GeometryTemplatesFromJSON(json['geometry-templates']),
        'unit_of_measurement': json['+unitOfMeasurement'] == null ? undefined : json['+unitOfMeasurement'],
        'simulations': json['+simulations'] == null ? undefined : ((json['+simulations'] as Array<any>).map(SimulationInfoFromJSON)),
        'num_objects': json['+num_objects'] == null ? undefined : json['+num_objects'],
        'num_surfaces': json['+num_surfaces'] == null ? undefined : json['+num_surfaces'],
    };
}

export function CityModelToJSON(json: any): CityModel {
    return CityModelToJSONTyped(json, false);
}

export function CityModelToJSONTyped(value?: CityModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'version': value['version'],
        'CityObjects': value['city_objects'] == null ? undefined : (mapValues(value['city_objects'], CityObjectToJSON)),
        'vertices': value['vertices'],
        'metadata': value['metadata'],
        'transform': value['transform'],
        'extensions': value['extensions'],
        'appearance': AppearanceObjectToJSON(value['appearance']),
        'geometry-templates': GeometryTemplatesToJSON(value['geometry_templates']),
        '+unitOfMeasurement': value['unit_of_measurement'],
        '+simulations': value['simulations'] == null ? undefined : ((value['simulations'] as Array<any>).map(SimulationInfoToJSON)),
        '+num_objects': value['num_objects'],
        '+num_surfaces': value['num_surfaces'],
    };
}

