/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CityJSONGeometryObjectType = {
    multi_point: 'MultiPoint',
    multi_line_string: 'MultiLineString',
    multi_surface: 'MultiSurface',
    composite_surface: 'CompositeSurface',
    solid: 'Solid',
    multi_solid: 'MultiSolid',
    composite_solid: 'CompositeSolid',
    geometry_instance: 'GeometryInstance'
} as const;
export type CityJSONGeometryObjectType = typeof CityJSONGeometryObjectType[keyof typeof CityJSONGeometryObjectType];


export function instanceOfCityJSONGeometryObjectType(value: any): boolean {
    for (const key in CityJSONGeometryObjectType) {
        if (Object.prototype.hasOwnProperty.call(CityJSONGeometryObjectType, key)) {
            if (CityJSONGeometryObjectType[key as keyof typeof CityJSONGeometryObjectType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CityJSONGeometryObjectTypeFromJSON(json: any): CityJSONGeometryObjectType {
    return CityJSONGeometryObjectTypeFromJSONTyped(json, false);
}

export function CityJSONGeometryObjectTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityJSONGeometryObjectType {
    return json as CityJSONGeometryObjectType;
}

export function CityJSONGeometryObjectTypeToJSON(value?: CityJSONGeometryObjectType | null): any {
    return value as any;
}

export function CityJSONGeometryObjectTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CityJSONGeometryObjectType {
    return value as CityJSONGeometryObjectType;
}

