/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Climate
 */
export interface Climate {
    /**
     * 
     * @type {number}
     * @memberof Climate
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Climate
     */
    year: number;
    /**
     * 
     * @type {string}
     * @memberof Climate
     */
    climate_file: string;
    /**
     * 
     * @type {number}
     * @memberof Climate
     */
    climate_scenario_id: number;
    /**
     * 
     * @type {number}
     * @memberof Climate
     */
    zone_id: number;
}

/**
 * Check if a given object implements the Climate interface.
 */
export function instanceOfClimate(value: object): value is Climate {
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('climate_file' in value) || value['climate_file'] === undefined) return false;
    if (!('climate_scenario_id' in value) || value['climate_scenario_id'] === undefined) return false;
    if (!('zone_id' in value) || value['zone_id'] === undefined) return false;
    return true;
}

export function ClimateFromJSON(json: any): Climate {
    return ClimateFromJSONTyped(json, false);
}

export function ClimateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Climate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'year': json['year'],
        'climate_file': json['climate_file'],
        'climate_scenario_id': json['climate_scenario_id'],
        'zone_id': json['zone_id'],
    };
}

export function ClimateToJSON(json: any): Climate {
    return ClimateToJSONTyped(json, false);
}

export function ClimateToJSONTyped(value?: Climate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'year': value['year'],
        'climate_file': value['climate_file'],
        'climate_scenario_id': value['climate_scenario_id'],
        'zone_id': value['zone_id'],
    };
}

