/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClimateScenario
 */
export interface ClimateScenario {
    /**
     * 
     * @type {number}
     * @memberof ClimateScenario
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ClimateScenario
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ClimateScenario
     */
    climate_file_postfix: string;
}

/**
 * Check if a given object implements the ClimateScenario interface.
 */
export function instanceOfClimateScenario(value: object): value is ClimateScenario {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('climate_file_postfix' in value) || value['climate_file_postfix'] === undefined) return false;
    return true;
}

export function ClimateScenarioFromJSON(json: any): ClimateScenario {
    return ClimateScenarioFromJSONTyped(json, false);
}

export function ClimateScenarioFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClimateScenario {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'climate_file_postfix': json['climate_file_postfix'],
    };
}

export function ClimateScenarioToJSON(json: any): ClimateScenario {
    return ClimateScenarioToJSONTyped(json, false);
}

export function ClimateScenarioToJSONTyped(value?: ClimateScenario | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'climate_file_postfix': value['climate_file_postfix'],
    };
}

