/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CoordinateSystem = {
    epsg_4326: 'EPSG:4326',
    epsg_2056: 'EPSG:2056',
    epsg_21781: 'EPSG:21781'
} as const;
export type CoordinateSystem = typeof CoordinateSystem[keyof typeof CoordinateSystem];


export function instanceOfCoordinateSystem(value: any): boolean {
    for (const key in CoordinateSystem) {
        if (Object.prototype.hasOwnProperty.call(CoordinateSystem, key)) {
            if (CoordinateSystem[key as keyof typeof CoordinateSystem] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CoordinateSystemFromJSON(json: any): CoordinateSystem {
    return CoordinateSystemFromJSONTyped(json, false);
}

export function CoordinateSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinateSystem {
    return json as CoordinateSystem;
}

export function CoordinateSystemToJSON(value?: CoordinateSystem | null): any {
    return value as any;
}

export function CoordinateSystemToJSONTyped(value: any, ignoreDiscriminator: boolean): CoordinateSystem {
    return value as CoordinateSystem;
}

