/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurveType } from './CurveType';
import {
    CurveTypeFromJSON,
    CurveTypeFromJSONTyped,
    CurveTypeToJSON,
    CurveTypeToJSONTyped,
} from './CurveType';
import type { MultiCurve } from './MultiCurve';
import {
    MultiCurveFromJSON,
    MultiCurveFromJSONTyped,
    MultiCurveToJSON,
    MultiCurveToJSONTyped,
} from './MultiCurve';

/**
 * 
 * @export
 * @interface Curve
 */
export interface Curve {
    /**
     * 
     * @type {number}
     * @memberof Curve
     */
    id?: number | null;
    /**
     * 
     * @type {CurveType}
     * @memberof Curve
     */
    curve_type?: CurveType;
    /**
     * 
     * @type {MultiCurve}
     * @memberof Curve
     */
    data: MultiCurve;
    /**
     * 
     * @type {number}
     * @memberof Curve
     */
    asset_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Curve
     */
    layer_id: number;
    /**
     * 
     * @type {number}
     * @memberof Curve
     */
    extent_id: number;
    /**
     * 
     * @type {number}
     * @memberof Curve
     */
    object_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Curve
     */
    parent_id?: number | null;
}



/**
 * Check if a given object implements the Curve interface.
 */
export function instanceOfCurve(value: object): value is Curve {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('asset_id' in value) || value['asset_id'] === undefined) return false;
    if (!('layer_id' in value) || value['layer_id'] === undefined) return false;
    if (!('extent_id' in value) || value['extent_id'] === undefined) return false;
    return true;
}

export function CurveFromJSON(json: any): Curve {
    return CurveFromJSONTyped(json, false);
}

export function CurveFromJSONTyped(json: any, ignoreDiscriminator: boolean): Curve {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'curve_type': json['curve_type'] == null ? undefined : CurveTypeFromJSON(json['curve_type']),
        'data': MultiCurveFromJSON(json['data']),
        'asset_id': json['asset_id'],
        'layer_id': json['layer_id'],
        'extent_id': json['extent_id'],
        'object_id': json['object_id'] == null ? undefined : json['object_id'],
        'parent_id': json['parent_id'] == null ? undefined : json['parent_id'],
    };
}

export function CurveToJSON(json: any): Curve {
    return CurveToJSONTyped(json, false);
}

export function CurveToJSONTyped(value?: Curve | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'curve_type': CurveTypeToJSON(value['curve_type']),
        'data': MultiCurveToJSON(value['data']),
        'asset_id': value['asset_id'],
        'layer_id': value['layer_id'],
        'extent_id': value['extent_id'],
        'object_id': value['object_id'],
        'parent_id': value['parent_id'],
    };
}

