/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CurveType = {
    NUMBER_0: 0
} as const;
export type CurveType = typeof CurveType[keyof typeof CurveType];


export function instanceOfCurveType(value: any): boolean {
    for (const key in CurveType) {
        if (Object.prototype.hasOwnProperty.call(CurveType, key)) {
            if (CurveType[key as keyof typeof CurveType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CurveTypeFromJSON(json: any): CurveType {
    return CurveTypeFromJSONTyped(json, false);
}

export function CurveTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurveType {
    return json as CurveType;
}

export function CurveTypeToJSON(value?: CurveType | null): any {
    return value as any;
}

export function CurveTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CurveType {
    return value as CurveType;
}

