/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Data source type enum. 
 * @export
 */
export const DataSourceType = {
    stac: 'STAC',
    remote_file: 'RemoteFile',
    geo_admin_api: 'GeoAdminAPI',
    madd: 'MADD',
    csv_file_repo: 'CSVFileRepo'
} as const;
export type DataSourceType = typeof DataSourceType[keyof typeof DataSourceType];


export function instanceOfDataSourceType(value: any): boolean {
    for (const key in DataSourceType) {
        if (Object.prototype.hasOwnProperty.call(DataSourceType, key)) {
            if (DataSourceType[key as keyof typeof DataSourceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DataSourceTypeFromJSON(json: any): DataSourceType {
    return DataSourceTypeFromJSONTyped(json, false);
}

export function DataSourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSourceType {
    return json as DataSourceType;
}

export function DataSourceTypeToJSON(value?: DataSourceType | null): any {
    return value as any;
}

export function DataSourceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DataSourceType {
    return value as DataSourceType;
}

