/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataSourceType } from './DataSourceType';
import {
    DataSourceTypeFromJSON,
    DataSourceTypeFromJSONTyped,
    DataSourceTypeToJSON,
    DataSourceTypeToJSONTyped,
} from './DataSourceType';

/**
 * Data source database element. 
 * @export
 * @interface DataSource
 */
export interface DataSource {
    /**
     * 
     * @type {number}
     * @memberof DataSource
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DataSource
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DataSource
     */
    title: string;
    /**
     * 
     * @type {DataSourceType}
     * @memberof DataSource
     */
    type: DataSourceType;
    /**
     * 
     * @type {string}
     * @memberof DataSource
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSource
     */
    path?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataSource
     */
    metadata_url?: string | null;
}



/**
 * Check if a given object implements the DataSource interface.
 */
export function instanceOfDataSource(value: object): value is DataSource {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function DataSourceFromJSON(json: any): DataSource {
    return DataSourceFromJSONTyped(json, false);
}

export function DataSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'title': json['title'],
        'type': DataSourceTypeFromJSON(json['type']),
        'url': json['url'] == null ? undefined : json['url'],
        'path': json['path'] == null ? undefined : json['path'],
        'metadata_url': json['metadata_url'] == null ? undefined : json['metadata_url'],
    };
}

export function DataSourceToJSON(json: any): DataSource {
    return DataSourceToJSONTyped(json, false);
}

export function DataSourceToJSONTyped(value?: DataSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'type': DataSourceTypeToJSON(value['type']),
        'url': value['url'],
        'path': value['path'],
        'metadata_url': value['metadata_url'],
    };
}

