/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType } from './OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType';
import {
    OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemTypeFromJSON,
    OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemTypeFromJSONTyped,
    OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemTypeToJSON,
    OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemTypeToJSONTyped,
} from './OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType';

/**
 * 
 * @export
 * @interface EnergyHeatPump
 */
export interface EnergyHeatPump {
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    id?: number | null;
    /**
     * 
     * @type {OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType}
     * @memberof EnergyHeatPump
     */
    type?: OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    object_id: number;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    energy_renovation_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    network_power_node_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    network_thermal_node_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    building_heat_source_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    building_cool_source_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    rated_power_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    technical_efficiency_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    target_temperature_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    source_temperature_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    depth_minimum_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    depth_maximum_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyHeatPump
     */
    thermal_diffusivity_attribute_id?: number | null;
}



/**
 * Check if a given object implements the EnergyHeatPump interface.
 */
export function instanceOfEnergyHeatPump(value: object): value is EnergyHeatPump {
    if (!('object_id' in value) || value['object_id'] === undefined) return false;
    return true;
}

export function EnergyHeatPumpFromJSON(json: any): EnergyHeatPump {
    return EnergyHeatPumpFromJSONTyped(json, false);
}

export function EnergyHeatPumpFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnergyHeatPump {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemTypeFromJSON(json['type']),
        'object_id': json['object_id'],
        'energy_renovation_id': json['energy_renovation_id'] == null ? undefined : json['energy_renovation_id'],
        'network_power_node_id': json['network_power_node_id'] == null ? undefined : json['network_power_node_id'],
        'network_thermal_node_id': json['network_thermal_node_id'] == null ? undefined : json['network_thermal_node_id'],
        'building_heat_source_id': json['building_heat_source_id'] == null ? undefined : json['building_heat_source_id'],
        'building_cool_source_id': json['building_cool_source_id'] == null ? undefined : json['building_cool_source_id'],
        'rated_power_attribute_id': json['rated_power_attribute_id'] == null ? undefined : json['rated_power_attribute_id'],
        'technical_efficiency_attribute_id': json['technical_efficiency_attribute_id'] == null ? undefined : json['technical_efficiency_attribute_id'],
        'target_temperature_attribute_id': json['target_temperature_attribute_id'] == null ? undefined : json['target_temperature_attribute_id'],
        'source_temperature_attribute_id': json['source_temperature_attribute_id'] == null ? undefined : json['source_temperature_attribute_id'],
        'depth_minimum_attribute_id': json['depth_minimum_attribute_id'] == null ? undefined : json['depth_minimum_attribute_id'],
        'depth_maximum_attribute_id': json['depth_maximum_attribute_id'] == null ? undefined : json['depth_maximum_attribute_id'],
        'thermal_diffusivity_attribute_id': json['thermal_diffusivity_attribute_id'] == null ? undefined : json['thermal_diffusivity_attribute_id'],
    };
}

export function EnergyHeatPumpToJSON(json: any): EnergyHeatPump {
    return EnergyHeatPumpToJSONTyped(json, false);
}

export function EnergyHeatPumpToJSONTyped(value?: EnergyHeatPump | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemTypeToJSON(value['type']),
        'object_id': value['object_id'],
        'energy_renovation_id': value['energy_renovation_id'],
        'network_power_node_id': value['network_power_node_id'],
        'network_thermal_node_id': value['network_thermal_node_id'],
        'building_heat_source_id': value['building_heat_source_id'],
        'building_cool_source_id': value['building_cool_source_id'],
        'rated_power_attribute_id': value['rated_power_attribute_id'],
        'technical_efficiency_attribute_id': value['technical_efficiency_attribute_id'],
        'target_temperature_attribute_id': value['target_temperature_attribute_id'],
        'source_temperature_attribute_id': value['source_temperature_attribute_id'],
        'depth_minimum_attribute_id': value['depth_minimum_attribute_id'],
        'depth_maximum_attribute_id': value['depth_maximum_attribute_id'],
        'thermal_diffusivity_attribute_id': value['thermal_diffusivity_attribute_id'],
    };
}

