/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnergyRenovation
 */
export interface EnergyRenovation {
    /**
     * 
     * @type {number}
     * @memberof EnergyRenovation
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyRenovation
     */
    building_id: number;
    /**
     * 
     * @type {number}
     * @memberof EnergyRenovation
     */
    scenario_id: number;
    /**
     * 
     * @type {number}
     * @memberof EnergyRenovation
     */
    scenario_year: number;
    /**
     * 
     * @type {boolean}
     * @memberof EnergyRenovation
     */
    wall_renovation: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EnergyRenovation
     */
    window_renovation: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EnergyRenovation
     */
    roof_renovation: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EnergyRenovation
     */
    floor_renovation: boolean;
}

/**
 * Check if a given object implements the EnergyRenovation interface.
 */
export function instanceOfEnergyRenovation(value: object): value is EnergyRenovation {
    if (!('building_id' in value) || value['building_id'] === undefined) return false;
    if (!('scenario_id' in value) || value['scenario_id'] === undefined) return false;
    if (!('scenario_year' in value) || value['scenario_year'] === undefined) return false;
    if (!('wall_renovation' in value) || value['wall_renovation'] === undefined) return false;
    if (!('window_renovation' in value) || value['window_renovation'] === undefined) return false;
    if (!('roof_renovation' in value) || value['roof_renovation'] === undefined) return false;
    if (!('floor_renovation' in value) || value['floor_renovation'] === undefined) return false;
    return true;
}

export function EnergyRenovationFromJSON(json: any): EnergyRenovation {
    return EnergyRenovationFromJSONTyped(json, false);
}

export function EnergyRenovationFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnergyRenovation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'building_id': json['building_id'],
        'scenario_id': json['scenario_id'],
        'scenario_year': json['scenario_year'],
        'wall_renovation': json['wall_renovation'],
        'window_renovation': json['window_renovation'],
        'roof_renovation': json['roof_renovation'],
        'floor_renovation': json['floor_renovation'],
    };
}

export function EnergyRenovationToJSON(json: any): EnergyRenovation {
    return EnergyRenovationToJSONTyped(json, false);
}

export function EnergyRenovationToJSONTyped(value?: EnergyRenovation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'building_id': value['building_id'],
        'scenario_id': value['scenario_id'],
        'scenario_year': value['scenario_year'],
        'wall_renovation': value['wall_renovation'],
        'window_renovation': value['window_renovation'],
        'roof_renovation': value['roof_renovation'],
        'floor_renovation': value['floor_renovation'],
    };
}

