/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType } from './OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType';
import {
    OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemTypeFromJSON,
    OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemTypeFromJSONTyped,
    OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemTypeToJSON,
    OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemTypeToJSONTyped,
} from './OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType';

/**
 * 
 * @export
 * @interface EnergyPhotovoltaicSystem
 */
export interface EnergyPhotovoltaicSystem {
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    id?: number | null;
    /**
     * 
     * @type {OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType}
     * @memberof EnergyPhotovoltaicSystem
     */
    type?: OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    object_id: number;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    energy_renovation_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    network_power_node_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    building_power_source_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    building_boundary_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    reference_efficiency_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    nominal_operating_cell_temperature_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    reference_temperature_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    maximum_power_voltage_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    voltage_temperature_coefficient_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    photovoltaic_ratio_attribute_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnergyPhotovoltaicSystem
     */
    photovoltaic_surface_attribute_id?: number | null;
}



/**
 * Check if a given object implements the EnergyPhotovoltaicSystem interface.
 */
export function instanceOfEnergyPhotovoltaicSystem(value: object): value is EnergyPhotovoltaicSystem {
    if (!('object_id' in value) || value['object_id'] === undefined) return false;
    return true;
}

export function EnergyPhotovoltaicSystemFromJSON(json: any): EnergyPhotovoltaicSystem {
    return EnergyPhotovoltaicSystemFromJSONTyped(json, false);
}

export function EnergyPhotovoltaicSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnergyPhotovoltaicSystem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemTypeFromJSON(json['type']),
        'object_id': json['object_id'],
        'energy_renovation_id': json['energy_renovation_id'] == null ? undefined : json['energy_renovation_id'],
        'network_power_node_id': json['network_power_node_id'] == null ? undefined : json['network_power_node_id'],
        'building_power_source_id': json['building_power_source_id'] == null ? undefined : json['building_power_source_id'],
        'building_boundary_id': json['building_boundary_id'] == null ? undefined : json['building_boundary_id'],
        'reference_efficiency_attribute_id': json['reference_efficiency_attribute_id'] == null ? undefined : json['reference_efficiency_attribute_id'],
        'nominal_operating_cell_temperature_attribute_id': json['nominal_operating_cell_temperature_attribute_id'] == null ? undefined : json['nominal_operating_cell_temperature_attribute_id'],
        'reference_temperature_attribute_id': json['reference_temperature_attribute_id'] == null ? undefined : json['reference_temperature_attribute_id'],
        'maximum_power_voltage_attribute_id': json['maximum_power_voltage_attribute_id'] == null ? undefined : json['maximum_power_voltage_attribute_id'],
        'voltage_temperature_coefficient_attribute_id': json['voltage_temperature_coefficient_attribute_id'] == null ? undefined : json['voltage_temperature_coefficient_attribute_id'],
        'photovoltaic_ratio_attribute_id': json['photovoltaic_ratio_attribute_id'] == null ? undefined : json['photovoltaic_ratio_attribute_id'],
        'photovoltaic_surface_attribute_id': json['photovoltaic_surface_attribute_id'] == null ? undefined : json['photovoltaic_surface_attribute_id'],
    };
}

export function EnergyPhotovoltaicSystemToJSON(json: any): EnergyPhotovoltaicSystem {
    return EnergyPhotovoltaicSystemToJSONTyped(json, false);
}

export function EnergyPhotovoltaicSystemToJSONTyped(value?: EnergyPhotovoltaicSystem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemTypeToJSON(value['type']),
        'object_id': value['object_id'],
        'energy_renovation_id': value['energy_renovation_id'],
        'network_power_node_id': value['network_power_node_id'],
        'building_power_source_id': value['building_power_source_id'],
        'building_boundary_id': value['building_boundary_id'],
        'reference_efficiency_attribute_id': value['reference_efficiency_attribute_id'],
        'nominal_operating_cell_temperature_attribute_id': value['nominal_operating_cell_temperature_attribute_id'],
        'reference_temperature_attribute_id': value['reference_temperature_attribute_id'],
        'maximum_power_voltage_attribute_id': value['maximum_power_voltage_attribute_id'],
        'voltage_temperature_coefficient_attribute_id': value['voltage_temperature_coefficient_attribute_id'],
        'photovoltaic_ratio_attribute_id': value['photovoltaic_ratio_attribute_id'],
        'photovoltaic_surface_attribute_id': value['photovoltaic_surface_attribute_id'],
    };
}

