/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoordinateSystem } from './CoordinateSystem';
import {
    CoordinateSystemFromJSON,
    CoordinateSystemFromJSONTyped,
    CoordinateSystemToJSON,
    CoordinateSystemToJSONTyped,
} from './CoordinateSystem';
import type { Polygon } from './Polygon';
import {
    PolygonFromJSON,
    PolygonFromJSONTyped,
    PolygonToJSON,
    PolygonToJSONTyped,
} from './Polygon';

/**
 * 
 * @export
 * @interface Extent
 */
export interface Extent {
    /**
     * 
     * @type {number}
     * @memberof Extent
     */
    id?: number | null;
    /**
     * 
     * @type {Polygon}
     * @memberof Extent
     */
    polygon: Polygon;
    /**
     * 
     * @type {CoordinateSystem}
     * @memberof Extent
     */
    coordinate_system?: CoordinateSystem;
}



/**
 * Check if a given object implements the Extent interface.
 */
export function instanceOfExtent(value: object): value is Extent {
    if (!('polygon' in value) || value['polygon'] === undefined) return false;
    return true;
}

export function ExtentFromJSON(json: any): Extent {
    return ExtentFromJSONTyped(json, false);
}

export function ExtentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Extent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'polygon': PolygonFromJSON(json['polygon']),
        'coordinate_system': json['coordinate_system'] == null ? undefined : CoordinateSystemFromJSON(json['coordinate_system']),
    };
}

export function ExtentToJSON(json: any): Extent {
    return ExtentToJSONTyped(json, false);
}

export function ExtentToJSONTyped(value?: Extent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'polygon': PolygonToJSON(value['polygon']),
        'coordinate_system': CoordinateSystemToJSON(value['coordinate_system']),
    };
}

