/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Feature
 */
export interface Feature {
    /**
     * 
     * @type {number}
     * @memberof Feature
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Feature
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Feature
     */
    items_url: string | null;
    /**
     * 
     * @type {string}
     * @memberof Feature
     */
    webpage_url: string | null;
    /**
     * 
     * @type {number}
     * @memberof Feature
     */
    dataset_id: number;
    /**
     * 
     * @type {number}
     * @memberof Feature
     */
    interval_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Feature
     */
    extent_id: number | null;
}

/**
 * Check if a given object implements the Feature interface.
 */
export function instanceOfFeature(value: object): value is Feature {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('items_url' in value) || value['items_url'] === undefined) return false;
    if (!('webpage_url' in value) || value['webpage_url'] === undefined) return false;
    if (!('dataset_id' in value) || value['dataset_id'] === undefined) return false;
    if (!('interval_id' in value) || value['interval_id'] === undefined) return false;
    if (!('extent_id' in value) || value['extent_id'] === undefined) return false;
    return true;
}

export function FeatureFromJSON(json: any): Feature {
    return FeatureFromJSONTyped(json, false);
}

export function FeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Feature {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'items_url': json['items_url'],
        'webpage_url': json['webpage_url'],
        'dataset_id': json['dataset_id'],
        'interval_id': json['interval_id'],
        'extent_id': json['extent_id'],
    };
}

export function FeatureToJSON(json: any): Feature {
    return FeatureToJSONTyped(json, false);
}

export function FeatureToJSONTyped(value?: Feature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'items_url': value['items_url'],
        'webpage_url': value['webpage_url'],
        'dataset_id': value['dataset_id'],
        'interval_id': value['interval_id'],
        'extent_id': value['extent_id'],
    };
}

