/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CityJSONGeometryBoundaries } from './CityJSONGeometryBoundaries';
import {
    CityJSONGeometryBoundariesFromJSON,
    CityJSONGeometryBoundariesFromJSONTyped,
    CityJSONGeometryBoundariesToJSON,
    CityJSONGeometryBoundariesToJSONTyped,
} from './CityJSONGeometryBoundaries';
import type { CityJSONSemantics } from './CityJSONSemantics';
import {
    CityJSONSemanticsFromJSON,
    CityJSONSemanticsFromJSONTyped,
    CityJSONSemanticsToJSON,
    CityJSONSemanticsToJSONTyped,
} from './CityJSONSemantics';
import type { CityJSONGeometryObjectTextureTheme } from './CityJSONGeometryObjectTextureTheme';
import {
    CityJSONGeometryObjectTextureThemeFromJSON,
    CityJSONGeometryObjectTextureThemeFromJSONTyped,
    CityJSONGeometryObjectTextureThemeToJSON,
    CityJSONGeometryObjectTextureThemeToJSONTyped,
} from './CityJSONGeometryObjectTextureTheme';
import type { CityJSONGeometryLevelOfDetail } from './CityJSONGeometryLevelOfDetail';
import {
    CityJSONGeometryLevelOfDetailFromJSON,
    CityJSONGeometryLevelOfDetailFromJSONTyped,
    CityJSONGeometryLevelOfDetailToJSON,
    CityJSONGeometryLevelOfDetailToJSONTyped,
} from './CityJSONGeometryLevelOfDetail';
import type { CityJSONGeometryObjectType } from './CityJSONGeometryObjectType';
import {
    CityJSONGeometryObjectTypeFromJSON,
    CityJSONGeometryObjectTypeFromJSONTyped,
    CityJSONGeometryObjectTypeToJSON,
    CityJSONGeometryObjectTypeToJSONTyped,
} from './CityJSONGeometryObjectType';
import type { CityJSONGeometryObjectMaterialTheme } from './CityJSONGeometryObjectMaterialTheme';
import {
    CityJSONGeometryObjectMaterialThemeFromJSON,
    CityJSONGeometryObjectMaterialThemeFromJSONTyped,
    CityJSONGeometryObjectMaterialThemeToJSON,
    CityJSONGeometryObjectMaterialThemeToJSONTyped,
} from './CityJSONGeometryObjectMaterialTheme';

/**
 * 
 * @export
 * @interface GeometryObject
 */
export interface GeometryObject {
    /**
     * 
     * @type {CityJSONGeometryObjectType}
     * @memberof GeometryObject
     */
    type: CityJSONGeometryObjectType;
    /**
     * 
     * @type {CityJSONGeometryLevelOfDetail}
     * @memberof GeometryObject
     */
    lod: CityJSONGeometryLevelOfDetail;
    /**
     * 
     * @type {CityJSONGeometryBoundaries}
     * @memberof GeometryObject
     */
    boundaries: CityJSONGeometryBoundaries;
    /**
     * 
     * @type {CityJSONSemantics}
     * @memberof GeometryObject
     */
    semantics?: CityJSONSemantics | null;
    /**
     * 
     * @type {{ [key: string]: CityJSONGeometryObjectMaterialTheme; }}
     * @memberof GeometryObject
     */
    material?: { [key: string]: CityJSONGeometryObjectMaterialTheme; } | null;
    /**
     * 
     * @type {{ [key: string]: CityJSONGeometryObjectTextureTheme; }}
     * @memberof GeometryObject
     */
    texture?: { [key: string]: CityJSONGeometryObjectTextureTheme; } | null;
    /**
     * 
     * @type {number}
     * @memberof GeometryObject
     */
    template?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GeometryObject
     */
    layer?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof GeometryObject
     */
    transformation_matrix?: Array<number> | null;
}



/**
 * Check if a given object implements the GeometryObject interface.
 */
export function instanceOfGeometryObject(value: object): value is GeometryObject {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('lod' in value) || value['lod'] === undefined) return false;
    if (!('boundaries' in value) || value['boundaries'] === undefined) return false;
    return true;
}

export function GeometryObjectFromJSON(json: any): GeometryObject {
    return GeometryObjectFromJSONTyped(json, false);
}

export function GeometryObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeometryObject {
    if (json == null) {
        return json;
    }
    return {
        
        'type': CityJSONGeometryObjectTypeFromJSON(json['type']),
        'lod': CityJSONGeometryLevelOfDetailFromJSON(json['lod']),
        'boundaries': CityJSONGeometryBoundariesFromJSON(json['boundaries']),
        'semantics': json['semantics'] == null ? undefined : CityJSONSemanticsFromJSON(json['semantics']),
        'material': json['material'] == null ? undefined : (mapValues(json['material'], CityJSONGeometryObjectMaterialThemeFromJSON)),
        'texture': json['texture'] == null ? undefined : (mapValues(json['texture'], CityJSONGeometryObjectTextureThemeFromJSON)),
        'template': json['template'] == null ? undefined : json['template'],
        'layer': json['+layer'] == null ? undefined : json['+layer'],
        'transformation_matrix': json['transformationMatrix'] == null ? undefined : json['transformationMatrix'],
    };
}

export function GeometryObjectToJSON(json: any): GeometryObject {
    return GeometryObjectToJSONTyped(json, false);
}

export function GeometryObjectToJSONTyped(value?: GeometryObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': CityJSONGeometryObjectTypeToJSON(value['type']),
        'lod': CityJSONGeometryLevelOfDetailToJSON(value['lod']),
        'boundaries': CityJSONGeometryBoundariesToJSON(value['boundaries']),
        'semantics': CityJSONSemanticsToJSON(value['semantics']),
        'material': value['material'] == null ? undefined : (mapValues(value['material'], CityJSONGeometryObjectMaterialThemeToJSON)),
        'texture': value['texture'] == null ? undefined : (mapValues(value['texture'], CityJSONGeometryObjectTextureThemeToJSON)),
        'template': value['template'],
        '+layer': value['layer'],
        'transformationMatrix': value['transformation_matrix'],
    };
}

