/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeometryObject } from './GeometryObject';
import {
    GeometryObjectFromJSON,
    GeometryObjectFromJSONTyped,
    GeometryObjectToJSON,
    GeometryObjectToJSONTyped,
} from './GeometryObject';

/**
 * 
 * @export
 * @interface GeometryTemplates
 */
export interface GeometryTemplates {
    /**
     * 
     * @type {Array<GeometryObject>}
     * @memberof GeometryTemplates
     */
    templates: Array<GeometryObject>;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof GeometryTemplates
     */
    vertices_templates?: Array<Array<number>>;
}

/**
 * Check if a given object implements the GeometryTemplates interface.
 */
export function instanceOfGeometryTemplates(value: object): value is GeometryTemplates {
    if (!('templates' in value) || value['templates'] === undefined) return false;
    return true;
}

export function GeometryTemplatesFromJSON(json: any): GeometryTemplates {
    return GeometryTemplatesFromJSONTyped(json, false);
}

export function GeometryTemplatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeometryTemplates {
    if (json == null) {
        return json;
    }
    return {
        
        'templates': ((json['templates'] as Array<any>).map(GeometryObjectFromJSON)),
        'vertices_templates': json['vertices-templates'] == null ? undefined : json['vertices-templates'],
    };
}

export function GeometryTemplatesToJSON(json: any): GeometryTemplates {
    return GeometryTemplatesToJSONTyped(json, false);
}

export function GeometryTemplatesToJSONTyped(value?: GeometryTemplates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templates': ((value['templates'] as Array<any>).map(GeometryObjectToJSON)),
        'vertices-templates': value['vertices_templates'],
    };
}

