/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LayerType = {
    elevation: 'elevation',
    geometry: 'geometry',
    raster: 'raster',
    data: 'data'
} as const;
export type LayerType = typeof LayerType[keyof typeof LayerType];


export function instanceOfLayerType(value: any): boolean {
    for (const key in LayerType) {
        if (Object.prototype.hasOwnProperty.call(LayerType, key)) {
            if (LayerType[key as keyof typeof LayerType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LayerTypeFromJSON(json: any): LayerType {
    return LayerTypeFromJSONTyped(json, false);
}

export function LayerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayerType {
    return json as LayerType;
}

export function LayerTypeToJSON(value?: LayerType | null): any {
    return value as any;
}

export function LayerTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): LayerType {
    return value as LayerType;
}

