/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LayerType } from './LayerType';
import {
    LayerTypeFromJSON,
    LayerTypeFromJSONTyped,
    LayerTypeToJSON,
    LayerTypeToJSONTyped,
} from './LayerType';

/**
 * 
 * @export
 * @interface Layer
 */
export interface Layer {
    /**
     * 
     * @type {number}
     * @memberof Layer
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Layer
     */
    name: string;
    /**
     * 
     * @type {LayerType}
     * @memberof Layer
     */
    type?: LayerType;
    /**
     * 
     * @type {number}
     * @memberof Layer
     */
    parent_id?: number | null;
}



/**
 * Check if a given object implements the Layer interface.
 */
export function instanceOfLayer(value: object): value is Layer {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function LayerFromJSON(json: any): Layer {
    return LayerFromJSONTyped(json, false);
}

export function LayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Layer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'type': json['type'] == null ? undefined : LayerTypeFromJSON(json['type']),
        'parent_id': json['parent_id'] == null ? undefined : json['parent_id'],
    };
}

export function LayerToJSON(json: any): Layer {
    return LayerToJSONTyped(json, false);
}

export function LayerToJSONTyped(value?: Layer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': LayerTypeToJSON(value['type']),
        'parent_id': value['parent_id'],
    };
}

