/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapCoordinate
 */
export interface MapCoordinate {
    /**
     * 
     * @type {number}
     * @memberof MapCoordinate
     */
    lat: number;
    /**
     * 
     * @type {number}
     * @memberof MapCoordinate
     */
    lng: number;
}

/**
 * Check if a given object implements the MapCoordinate interface.
 */
export function instanceOfMapCoordinate(value: object): value is MapCoordinate {
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lng' in value) || value['lng'] === undefined) return false;
    return true;
}

export function MapCoordinateFromJSON(json: any): MapCoordinate {
    return MapCoordinateFromJSONTyped(json, false);
}

export function MapCoordinateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapCoordinate {
    if (json == null) {
        return json;
    }
    return {
        
        'lat': json['lat'],
        'lng': json['lng'],
    };
}

export function MapCoordinateToJSON(json: any): MapCoordinate {
    return MapCoordinateToJSONTyped(json, false);
}

export function MapCoordinateToJSONTyped(value?: MapCoordinate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lat': value['lat'],
        'lng': value['lng'],
    };
}

