/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MapCoordinate } from './MapCoordinate';
import {
    MapCoordinateFromJSON,
    MapCoordinateFromJSONTyped,
    MapCoordinateToJSON,
    MapCoordinateToJSONTyped,
} from './MapCoordinate';

/**
 * 
 * @export
 * @interface MapZone
 */
export interface MapZone {
    /**
     * 
     * @type {string}
     * @memberof MapZone
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MapZone
     */
    municipality_name: string;
    /**
     * 
     * @type {Array<MapCoordinate>}
     * @memberof MapZone
     */
    coordinates: Array<MapCoordinate>;
}

/**
 * Check if a given object implements the MapZone interface.
 */
export function instanceOfMapZone(value: object): value is MapZone {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('municipality_name' in value) || value['municipality_name'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function MapZoneFromJSON(json: any): MapZone {
    return MapZoneFromJSONTyped(json, false);
}

export function MapZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapZone {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'municipality_name': json['municipality_name'],
        'coordinates': ((json['coordinates'] as Array<any>).map(MapCoordinateFromJSON)),
    };
}

export function MapZoneToJSON(json: any): MapZone {
    return MapZoneToJSONTyped(json, false);
}

export function MapZoneToJSONTyped(value?: MapZone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'municipality_name': value['municipality_name'],
        'coordinates': ((value['coordinates'] as Array<any>).map(MapCoordinateToJSON)),
    };
}

