/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaterialObject
 */
export interface MaterialObject {
    /**
     * 
     * @type {string}
     * @memberof MaterialObject
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof MaterialObject
     */
    ambient_intensity?: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof MaterialObject
     */
    diffuse_color?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof MaterialObject
     */
    emissive_color?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof MaterialObject
     */
    specular_color?: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof MaterialObject
     */
    shininess?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MaterialObject
     */
    transparency?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof MaterialObject
     */
    is_smooth?: boolean | null;
}

/**
 * Check if a given object implements the MaterialObject interface.
 */
export function instanceOfMaterialObject(value: object): value is MaterialObject {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MaterialObjectFromJSON(json: any): MaterialObject {
    return MaterialObjectFromJSONTyped(json, false);
}

export function MaterialObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaterialObject {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ambient_intensity': json['ambientIntensity'] == null ? undefined : json['ambientIntensity'],
        'diffuse_color': json['diffuseColor'] == null ? undefined : json['diffuseColor'],
        'emissive_color': json['emissiveColor'] == null ? undefined : json['emissiveColor'],
        'specular_color': json['specularColor'] == null ? undefined : json['specularColor'],
        'shininess': json['shininess'] == null ? undefined : json['shininess'],
        'transparency': json['transparency'] == null ? undefined : json['transparency'],
        'is_smooth': json['isSmooth'] == null ? undefined : json['isSmooth'],
    };
}

export function MaterialObjectToJSON(json: any): MaterialObject {
    return MaterialObjectToJSONTyped(json, false);
}

export function MaterialObjectToJSONTyped(value?: MaterialObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'ambientIntensity': value['ambient_intensity'],
        'diffuseColor': value['diffuse_color'],
        'emissiveColor': value['emissive_color'],
        'specularColor': value['specular_color'],
        'shininess': value['shininess'],
        'transparency': value['transparency'],
        'isSmooth': value['is_smooth'],
    };
}

