/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelObject
 */
export interface ModelObject {
    /**
     * 
     * @type {number}
     * @memberof ModelObject
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ModelObject
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ModelObject
     */
    object_type_id: number;
    /**
     * 
     * @type {number}
     * @memberof ModelObject
     */
    zone_id: number;
    /**
     * 
     * @type {number}
     * @memberof ModelObject
     */
    layer_id: number;
    /**
     * 
     * @type {number}
     * @memberof ModelObject
     */
    parent_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ModelObject
     */
    scenario_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ModelObject
     */
    scenario_year?: number | null;
}

/**
 * Check if a given object implements the ModelObject interface.
 */
export function instanceOfModelObject(value: object): value is ModelObject {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('object_type_id' in value) || value['object_type_id'] === undefined) return false;
    if (!('zone_id' in value) || value['zone_id'] === undefined) return false;
    if (!('layer_id' in value) || value['layer_id'] === undefined) return false;
    return true;
}

export function ModelObjectFromJSON(json: any): ModelObject {
    return ModelObjectFromJSONTyped(json, false);
}

export function ModelObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelObject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'object_type_id': json['object_type_id'],
        'zone_id': json['zone_id'],
        'layer_id': json['layer_id'],
        'parent_id': json['parent_id'] == null ? undefined : json['parent_id'],
        'scenario_id': json['scenario_id'] == null ? undefined : json['scenario_id'],
        'scenario_year': json['scenario_year'] == null ? undefined : json['scenario_year'],
    };
}

export function ModelObjectToJSON(json: any): ModelObject {
    return ModelObjectToJSONTyped(json, false);
}

export function ModelObjectToJSONTyped(value?: ModelObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'object_type_id': value['object_type_id'],
        'zone_id': value['zone_id'],
        'layer_id': value['layer_id'],
        'parent_id': value['parent_id'],
        'scenario_id': value['scenario_id'],
        'scenario_year': value['scenario_year'],
    };
}

