/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bbox } from './Bbox';
import {
    BboxFromJSON,
    BboxFromJSONTyped,
    BboxToJSON,
    BboxToJSONTyped,
} from './Bbox';
import type { MultiCurveCoordinatesInnerInner } from './MultiCurveCoordinatesInnerInner';
import {
    MultiCurveCoordinatesInnerInnerFromJSON,
    MultiCurveCoordinatesInnerInnerFromJSONTyped,
    MultiCurveCoordinatesInnerInnerToJSON,
    MultiCurveCoordinatesInnerInnerToJSONTyped,
} from './MultiCurveCoordinatesInnerInner';

/**
 * 
 * @export
 * @interface MultiCurve
 */
export interface MultiCurve {
    /**
     * 
     * @type {Bbox}
     * @memberof MultiCurve
     */
    bbox?: Bbox | null;
    /**
     * 
     * @type {string}
     * @memberof MultiCurve
     */
    type: MultiCurveTypeEnum;
    /**
     * 
     * @type {Array<Array<MultiCurveCoordinatesInnerInner>>}
     * @memberof MultiCurve
     */
    coordinates: Array<Array<MultiCurveCoordinatesInnerInner>>;
}


/**
 * @export
 */
export const MultiCurveTypeEnum = {
    multi_line_string: 'MultiLineString'
} as const;
export type MultiCurveTypeEnum = typeof MultiCurveTypeEnum[keyof typeof MultiCurveTypeEnum];


/**
 * Check if a given object implements the MultiCurve interface.
 */
export function instanceOfMultiCurve(value: object): value is MultiCurve {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function MultiCurveFromJSON(json: any): MultiCurve {
    return MultiCurveFromJSONTyped(json, false);
}

export function MultiCurveFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiCurve {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'] == null ? undefined : BboxFromJSON(json['bbox']),
        'type': json['type'],
        'coordinates': json['coordinates'],
    };
}

export function MultiCurveToJSON(json: any): MultiCurve {
    return MultiCurveToJSONTyped(json, false);
}

export function MultiCurveToJSONTyped(value?: MultiCurve | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': BboxToJSON(value['bbox']),
        'type': value['type'],
        'coordinates': value['coordinates'],
    };
}

