/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bbox } from './Bbox';
import {
    BboxFromJSON,
    BboxFromJSONTyped,
    BboxToJSON,
    BboxToJSONTyped,
} from './Bbox';
import type { MultiCurveCoordinatesInnerInner } from './MultiCurveCoordinatesInnerInner';
import {
    MultiCurveCoordinatesInnerInnerFromJSON,
    MultiCurveCoordinatesInnerInnerFromJSONTyped,
    MultiCurveCoordinatesInnerInnerToJSON,
    MultiCurveCoordinatesInnerInnerToJSONTyped,
} from './MultiCurveCoordinatesInnerInner';

/**
 * 
 * @export
 * @interface MultiPoint
 */
export interface MultiPoint {
    /**
     * 
     * @type {Bbox}
     * @memberof MultiPoint
     */
    bbox?: Bbox | null;
    /**
     * 
     * @type {string}
     * @memberof MultiPoint
     */
    type: MultiPointTypeEnum;
    /**
     * 
     * @type {Array<MultiCurveCoordinatesInnerInner>}
     * @memberof MultiPoint
     */
    coordinates: Array<MultiCurveCoordinatesInnerInner>;
}


/**
 * @export
 */
export const MultiPointTypeEnum = {
    multi_point: 'MultiPoint'
} as const;
export type MultiPointTypeEnum = typeof MultiPointTypeEnum[keyof typeof MultiPointTypeEnum];


/**
 * Check if a given object implements the MultiPoint interface.
 */
export function instanceOfMultiPoint(value: object): value is MultiPoint {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function MultiPointFromJSON(json: any): MultiPoint {
    return MultiPointFromJSONTyped(json, false);
}

export function MultiPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'] == null ? undefined : BboxFromJSON(json['bbox']),
        'type': json['type'],
        'coordinates': ((json['coordinates'] as Array<any>).map(MultiCurveCoordinatesInnerInnerFromJSON)),
    };
}

export function MultiPointToJSON(json: any): MultiPoint {
    return MultiPointToJSONTyped(json, false);
}

export function MultiPointToJSONTyped(value?: MultiPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': BboxToJSON(value['bbox']),
        'type': value['type'],
        'coordinates': ((value['coordinates'] as Array<any>).map(MultiCurveCoordinatesInnerInnerToJSON)),
    };
}

