/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultiCurveCoordinatesInnerInner
 */
export interface MultiCurveCoordinatesInnerInner {
}

/**
 * Check if a given object implements the MultiCurveCoordinatesInnerInner interface.
 */
export function instanceOfMultiCurveCoordinatesInnerInner(value: object): value is MultiCurveCoordinatesInnerInner {
    return true;
}

export function MultiCurveCoordinatesInnerInnerFromJSON(json: any): MultiCurveCoordinatesInnerInner {
    return MultiCurveCoordinatesInnerInnerFromJSONTyped(json, false);
}

export function MultiCurveCoordinatesInnerInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiCurveCoordinatesInnerInner {
    return json;
}

export function MultiCurveCoordinatesInnerInnerToJSON(json: any): MultiCurveCoordinatesInnerInner {
    return MultiCurveCoordinatesInnerInnerToJSONTyped(json, false);
}

export function MultiCurveCoordinatesInnerInnerToJSONTyped(value?: MultiCurveCoordinatesInnerInner | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

