/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bbox } from './Bbox';
import {
    BboxFromJSON,
    BboxFromJSONTyped,
    BboxToJSON,
    BboxToJSONTyped,
} from './Bbox';
import type { MultiCurveCoordinatesInnerInner } from './MultiCurveCoordinatesInnerInner';
import {
    MultiCurveCoordinatesInnerInnerFromJSON,
    MultiCurveCoordinatesInnerInnerFromJSONTyped,
    MultiCurveCoordinatesInnerInnerToJSON,
    MultiCurveCoordinatesInnerInnerToJSONTyped,
} from './MultiCurveCoordinatesInnerInner';

/**
 * 
 * @export
 * @interface MultiPolygon
 */
export interface MultiPolygon {
    /**
     * 
     * @type {Bbox}
     * @memberof MultiPolygon
     */
    bbox?: Bbox | null;
    /**
     * 
     * @type {string}
     * @memberof MultiPolygon
     */
    type: MultiPolygonTypeEnum;
    /**
     * 
     * @type {Array<Array<Array<MultiCurveCoordinatesInnerInner>>>}
     * @memberof MultiPolygon
     */
    coordinates: Array<Array<Array<MultiCurveCoordinatesInnerInner>>>;
}


/**
 * @export
 */
export const MultiPolygonTypeEnum = {
    multi_polygon: 'MultiPolygon'
} as const;
export type MultiPolygonTypeEnum = typeof MultiPolygonTypeEnum[keyof typeof MultiPolygonTypeEnum];


/**
 * Check if a given object implements the MultiPolygon interface.
 */
export function instanceOfMultiPolygon(value: object): value is MultiPolygon {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function MultiPolygonFromJSON(json: any): MultiPolygon {
    return MultiPolygonFromJSONTyped(json, false);
}

export function MultiPolygonFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiPolygon {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'] == null ? undefined : BboxFromJSON(json['bbox']),
        'type': json['type'],
        'coordinates': json['coordinates'],
    };
}

export function MultiPolygonToJSON(json: any): MultiPolygon {
    return MultiPolygonToJSONTyped(json, false);
}

export function MultiPolygonToJSONTyped(value?: MultiPolygon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': BboxToJSON(value['bbox']),
        'type': value['type'],
        'coordinates': value['coordinates'],
    };
}

