/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectType
 */
export interface ObjectType {
    /**
     * 
     * @type {number}
     * @memberof ObjectType
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ObjectType
     */
    name: string;
}

/**
 * Check if a given object implements the ObjectType interface.
 */
export function instanceOfObjectType(value: object): value is ObjectType {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ObjectTypeFromJSON(json: any): ObjectType {
    return ObjectTypeFromJSONTyped(json, false);
}

export function ObjectTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
    };
}

export function ObjectTypeToJSON(json: any): ObjectType {
    return ObjectTypeToJSONTyped(json, false);
}

export function ObjectTypeToJSONTyped(value?: ObjectType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

