/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType = {
    none: 'none',
    roof_photovoltaic_system: 'roof_photovoltaic_system',
    wall_photovoltaic_system: 'wall_photovoltaic_system'
} as const;
export type OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType = typeof OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType[keyof typeof OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType];


export function instanceOfOpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType(value: any): boolean {
    for (const key in OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType) {
        if (Object.prototype.hasOwnProperty.call(OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType, key)) {
            if (OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType[key as keyof typeof OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemTypeFromJSON(json: any): OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType {
    return OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemTypeFromJSONTyped(json, false);
}

export function OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType {
    return json as OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType;
}

export function OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemTypeToJSON(value?: OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType | null): any {
    return value as any;
}

export function OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType {
    return value as OpenbeersModelsEnergyPhotovoltaicSystemEnergyPhotovoltaicSystemType;
}

