/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType = typeof OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType[keyof typeof OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType];


export function instanceOfOpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType(value: any): boolean {
    for (const key in OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType) {
        if (Object.prototype.hasOwnProperty.call(OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType, key)) {
            if (OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType[key as keyof typeof OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemTypeFromJSON(json: any): OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType {
    return OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemTypeFromJSONTyped(json, false);
}

export function OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType {
    return json as OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType;
}

export function OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemTypeToJSON(value?: OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType | null): any {
    return value as any;
}

export function OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType {
    return value as OpenbeersModelsEnergyHeatPumpEnergyPhotovoltaicSystemType;
}

