/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultiPoint } from './MultiPoint';
import {
    MultiPointFromJSON,
    MultiPointFromJSONTyped,
    MultiPointToJSON,
    MultiPointToJSONTyped,
} from './MultiPoint';
import type { PointType } from './PointType';
import {
    PointTypeFromJSON,
    PointTypeFromJSONTyped,
    PointTypeToJSON,
    PointTypeToJSONTyped,
} from './PointType';

/**
 * 
 * @export
 * @interface Point
 */
export interface Point {
    /**
     * 
     * @type {number}
     * @memberof Point
     */
    id?: number | null;
    /**
     * 
     * @type {PointType}
     * @memberof Point
     */
    point_type?: PointType;
    /**
     * 
     * @type {MultiPoint}
     * @memberof Point
     */
    data: MultiPoint;
    /**
     * 
     * @type {number}
     * @memberof Point
     */
    asset_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Point
     */
    layer_id: number;
    /**
     * 
     * @type {number}
     * @memberof Point
     */
    extent_id: number;
    /**
     * 
     * @type {number}
     * @memberof Point
     */
    object_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Point
     */
    parent_id?: number | null;
}



/**
 * Check if a given object implements the Point interface.
 */
export function instanceOfPoint(value: object): value is Point {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('asset_id' in value) || value['asset_id'] === undefined) return false;
    if (!('layer_id' in value) || value['layer_id'] === undefined) return false;
    if (!('extent_id' in value) || value['extent_id'] === undefined) return false;
    return true;
}

export function PointFromJSON(json: any): Point {
    return PointFromJSONTyped(json, false);
}

export function PointFromJSONTyped(json: any, ignoreDiscriminator: boolean): Point {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'point_type': json['point_type'] == null ? undefined : PointTypeFromJSON(json['point_type']),
        'data': MultiPointFromJSON(json['data']),
        'asset_id': json['asset_id'],
        'layer_id': json['layer_id'],
        'extent_id': json['extent_id'],
        'object_id': json['object_id'] == null ? undefined : json['object_id'],
        'parent_id': json['parent_id'] == null ? undefined : json['parent_id'],
    };
}

export function PointToJSON(json: any): Point {
    return PointToJSONTyped(json, false);
}

export function PointToJSONTyped(value?: Point | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'point_type': PointTypeToJSON(value['point_type']),
        'data': MultiPointToJSON(value['data']),
        'asset_id': value['asset_id'],
        'layer_id': value['layer_id'],
        'extent_id': value['extent_id'],
        'object_id': value['object_id'],
        'parent_id': value['parent_id'],
    };
}

