/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PointType = {
    NUMBER_0: 0
} as const;
export type PointType = typeof PointType[keyof typeof PointType];


export function instanceOfPointType(value: any): boolean {
    for (const key in PointType) {
        if (Object.prototype.hasOwnProperty.call(PointType, key)) {
            if (PointType[key as keyof typeof PointType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PointTypeFromJSON(json: any): PointType {
    return PointTypeFromJSONTyped(json, false);
}

export function PointTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointType {
    return json as PointType;
}

export function PointTypeToJSON(value?: PointType | null): any {
    return value as any;
}

export function PointTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PointType {
    return value as PointType;
}

