/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PowerPlant
 */
export interface PowerPlant {
    /**
     * 
     * @type {number}
     * @memberof PowerPlant
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PowerPlant
     */
    object_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof PowerPlant
     */
    output_node_id: number | null;
}

/**
 * Check if a given object implements the PowerPlant interface.
 */
export function instanceOfPowerPlant(value: object): value is PowerPlant {
    if (!('object_id' in value) || value['object_id'] === undefined) return false;
    if (!('output_node_id' in value) || value['output_node_id'] === undefined) return false;
    return true;
}

export function PowerPlantFromJSON(json: any): PowerPlant {
    return PowerPlantFromJSONTyped(json, false);
}

export function PowerPlantFromJSONTyped(json: any, ignoreDiscriminator: boolean): PowerPlant {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'object_id': json['object_id'],
        'output_node_id': json['output_node_id'],
    };
}

export function PowerPlantToJSON(json: any): PowerPlant {
    return PowerPlantToJSONTyped(json, false);
}

export function PowerPlantToJSONTyped(value?: PowerPlant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'object_id': value['object_id'],
        'output_node_id': value['output_node_id'],
    };
}

