/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RasterType } from './RasterType';
import {
    RasterTypeFromJSON,
    RasterTypeFromJSONTyped,
    RasterTypeToJSON,
    RasterTypeToJSONTyped,
} from './RasterType';

/**
 * 
 * @export
 * @interface Raster
 */
export interface Raster {
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    id?: number | null;
    /**
     * 
     * @type {RasterType}
     * @memberof Raster
     */
    type?: RasterType;
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    size_x: number;
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    size_y: number;
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    scale_x: number;
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    scale_y: number;
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    pos_x: number;
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    pos_y: number;
    /**
     * 
     * @type {Array<any>}
     * @memberof Raster
     */
    data: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    asset_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    layer_id: number;
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    extent_id: number;
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    object_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Raster
     */
    parent_id?: number | null;
}



/**
 * Check if a given object implements the Raster interface.
 */
export function instanceOfRaster(value: object): value is Raster {
    if (!('size_x' in value) || value['size_x'] === undefined) return false;
    if (!('size_y' in value) || value['size_y'] === undefined) return false;
    if (!('scale_x' in value) || value['scale_x'] === undefined) return false;
    if (!('scale_y' in value) || value['scale_y'] === undefined) return false;
    if (!('pos_x' in value) || value['pos_x'] === undefined) return false;
    if (!('pos_y' in value) || value['pos_y'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('asset_id' in value) || value['asset_id'] === undefined) return false;
    if (!('layer_id' in value) || value['layer_id'] === undefined) return false;
    if (!('extent_id' in value) || value['extent_id'] === undefined) return false;
    return true;
}

export function RasterFromJSON(json: any): Raster {
    return RasterFromJSONTyped(json, false);
}

export function RasterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Raster {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : RasterTypeFromJSON(json['type']),
        'size_x': json['size_x'],
        'size_y': json['size_y'],
        'scale_x': json['scale_x'],
        'scale_y': json['scale_y'],
        'pos_x': json['pos_x'],
        'pos_y': json['pos_y'],
        'data': json['data'],
        'asset_id': json['asset_id'],
        'layer_id': json['layer_id'],
        'extent_id': json['extent_id'],
        'object_id': json['object_id'] == null ? undefined : json['object_id'],
        'parent_id': json['parent_id'] == null ? undefined : json['parent_id'],
    };
}

export function RasterToJSON(json: any): Raster {
    return RasterToJSONTyped(json, false);
}

export function RasterToJSONTyped(value?: Raster | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': RasterTypeToJSON(value['type']),
        'size_x': value['size_x'],
        'size_y': value['size_y'],
        'scale_x': value['scale_x'],
        'scale_y': value['scale_y'],
        'pos_x': value['pos_x'],
        'pos_y': value['pos_y'],
        'data': value['data'],
        'asset_id': value['asset_id'],
        'layer_id': value['layer_id'],
        'extent_id': value['extent_id'],
        'object_id': value['object_id'],
        'parent_id': value['parent_id'],
    };
}

