/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RasterType = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type RasterType = typeof RasterType[keyof typeof RasterType];


export function instanceOfRasterType(value: any): boolean {
    for (const key in RasterType) {
        if (Object.prototype.hasOwnProperty.call(RasterType, key)) {
            if (RasterType[key as keyof typeof RasterType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RasterTypeFromJSON(json: any): RasterType {
    return RasterTypeFromJSONTyped(json, false);
}

export function RasterTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RasterType {
    return json as RasterType;
}

export function RasterTypeToJSON(value?: RasterType | null): any {
    return value as any;
}

export function RasterTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): RasterType {
    return value as RasterType;
}

