/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppearanceObject } from './AppearanceObject';
import {
    AppearanceObjectFromJSON,
    AppearanceObjectFromJSONTyped,
    AppearanceObjectToJSON,
    AppearanceObjectToJSONTyped,
} from './AppearanceObject';
import type { CityObject } from './CityObject';
import {
    CityObjectFromJSON,
    CityObjectFromJSONTyped,
    CityObjectToJSON,
    CityObjectToJSONTyped,
} from './CityObject';
import type { CityModel } from './CityModel';
import {
    CityModelFromJSON,
    CityModelFromJSONTyped,
    CityModelToJSON,
    CityModelToJSONTyped,
} from './CityModel';
import type { GeometryTemplates } from './GeometryTemplates';
import {
    GeometryTemplatesFromJSON,
    GeometryTemplatesFromJSONTyped,
    GeometryTemplatesToJSON,
    GeometryTemplatesToJSONTyped,
} from './GeometryTemplates';
import type { CityFeature } from './CityFeature';
import {
    CityFeatureFromJSON,
    CityFeatureFromJSONTyped,
    CityFeatureToJSON,
    CityFeatureToJSONTyped,
} from './CityFeature';
import type { SimulationInfo } from './SimulationInfo';
import {
    SimulationInfoFromJSON,
    SimulationInfoFromJSONTyped,
    SimulationInfoToJSON,
    SimulationInfoToJSONTyped,
} from './SimulationInfo';

/**
 * 
 * @export
 * @interface ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
 */
export interface ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet {
    /**
     * 
     * @type {string}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    type?: ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    version?: ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetVersionEnum;
    /**
     * 
     * @type {{ [key: string]: CityObject; }}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    city_objects?: { [key: string]: CityObject; };
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    vertices?: Array<Array<number>>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: Array<number>; }}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    transform?: { [key: string]: Array<number>; };
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    extensions?: { [key: string]: { [key: string]: string; }; };
    /**
     * 
     * @type {AppearanceObject}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    appearance?: AppearanceObject;
    /**
     * 
     * @type {GeometryTemplates}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    geometry_templates?: GeometryTemplates;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    unit_of_measurement?: { [key: string]: string; };
    /**
     * 
     * @type {Array<SimulationInfo>}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    simulations?: Array<SimulationInfo>;
    /**
     * 
     * @type {number}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    num_objects?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    num_surfaces?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet
     */
    id: string;
}


/**
 * @export
 */
export const ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetTypeEnum = {
    city_json: 'CityJSON',
    city_json_feature: 'CityJSONFeature'
} as const;
export type ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetTypeEnum = typeof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetTypeEnum[keyof typeof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetTypeEnum];

/**
 * @export
 */
export const ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetVersionEnum = {
    _2_0: '2.0'
} as const;
export type ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetVersionEnum = typeof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetVersionEnum[keyof typeof ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetVersionEnum];


/**
 * Check if a given object implements the ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet interface.
 */
export function instanceOfResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet(value: object): value is ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetFromJSON(json: any): ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet {
    return ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetFromJSONTyped(json, false);
}

export function ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'version': json['version'] == null ? undefined : json['version'],
        'city_objects': json['CityObjects'] == null ? undefined : (mapValues(json['CityObjects'], CityObjectFromJSON)),
        'vertices': json['vertices'] == null ? undefined : json['vertices'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'transform': json['transform'] == null ? undefined : json['transform'],
        'extensions': json['extensions'] == null ? undefined : json['extensions'],
        'appearance': json['appearance'] == null ? undefined : AppearanceObjectFromJSON(json['appearance']),
        'geometry_templates': json['geometry-templates'] == null ? undefined : GeometryTemplatesFromJSON(json['geometry-templates']),
        'unit_of_measurement': json['+unitOfMeasurement'] == null ? undefined : json['+unitOfMeasurement'],
        'simulations': json['+simulations'] == null ? undefined : ((json['+simulations'] as Array<any>).map(SimulationInfoFromJSON)),
        'num_objects': json['+num_objects'] == null ? undefined : json['+num_objects'],
        'num_surfaces': json['+num_surfaces'] == null ? undefined : json['+num_surfaces'],
        'id': json['id'],
    };
}

export function ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetToJSON(json: any): ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet {
    return ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetToJSONTyped(json, false);
}

export function ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGetToJSONTyped(value?: ResponseGetCityjsonZoneLayerFeaturesApiCityjsonZoneZoneIdLayerLayerIdFeaturesGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'version': value['version'],
        'CityObjects': value['city_objects'] == null ? undefined : (mapValues(value['city_objects'], CityObjectToJSON)),
        'vertices': value['vertices'],
        'metadata': value['metadata'],
        'transform': value['transform'],
        'extensions': value['extensions'],
        'appearance': AppearanceObjectToJSON(value['appearance']),
        'geometry-templates': GeometryTemplatesToJSON(value['geometry_templates']),
        '+unitOfMeasurement': value['unit_of_measurement'],
        '+simulations': value['simulations'] == null ? undefined : ((value['simulations'] as Array<any>).map(SimulationInfoToJSON)),
        '+num_objects': value['num_objects'],
        '+num_surfaces': value['num_surfaces'],
        'id': value['id'],
    };
}

