/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseNewZoneApiZoneNewPostAnyOfValue
 */
export interface ResponseNewZoneApiZoneNewPostAnyOfValue {
}

/**
 * Check if a given object implements the ResponseNewZoneApiZoneNewPostAnyOfValue interface.
 */
export function instanceOfResponseNewZoneApiZoneNewPostAnyOfValue(value: object): value is ResponseNewZoneApiZoneNewPostAnyOfValue {
    return true;
}

export function ResponseNewZoneApiZoneNewPostAnyOfValueFromJSON(json: any): ResponseNewZoneApiZoneNewPostAnyOfValue {
    return ResponseNewZoneApiZoneNewPostAnyOfValueFromJSONTyped(json, false);
}

export function ResponseNewZoneApiZoneNewPostAnyOfValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseNewZoneApiZoneNewPostAnyOfValue {
    return json;
}

export function ResponseNewZoneApiZoneNewPostAnyOfValueToJSON(json: any): ResponseNewZoneApiZoneNewPostAnyOfValue {
    return ResponseNewZoneApiZoneNewPostAnyOfValueToJSONTyped(json, false);
}

export function ResponseNewZoneApiZoneNewPostAnyOfValueToJSONTyped(value?: ResponseNewZoneApiZoneNewPostAnyOfValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

