/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseNewZoneApiZoneNewPostAnyOfValue } from './ResponseNewZoneApiZoneNewPostAnyOfValue';
import {
    ResponseNewZoneApiZoneNewPostAnyOfValueFromJSON,
    ResponseNewZoneApiZoneNewPostAnyOfValueFromJSONTyped,
    ResponseNewZoneApiZoneNewPostAnyOfValueToJSON,
    ResponseNewZoneApiZoneNewPostAnyOfValueToJSONTyped,
} from './ResponseNewZoneApiZoneNewPostAnyOfValue';

/**
 * 
 * @export
 * @interface ResponseNewZoneApiZoneNewPost
 */
export interface ResponseNewZoneApiZoneNewPost {
}

/**
 * Check if a given object implements the ResponseNewZoneApiZoneNewPost interface.
 */
export function instanceOfResponseNewZoneApiZoneNewPost(value: object): value is ResponseNewZoneApiZoneNewPost {
    return true;
}

export function ResponseNewZoneApiZoneNewPostFromJSON(json: any): ResponseNewZoneApiZoneNewPost {
    return ResponseNewZoneApiZoneNewPostFromJSONTyped(json, false);
}

export function ResponseNewZoneApiZoneNewPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseNewZoneApiZoneNewPost {
    return json;
}

export function ResponseNewZoneApiZoneNewPostToJSON(json: any): ResponseNewZoneApiZoneNewPost {
    return ResponseNewZoneApiZoneNewPostToJSONTyped(json, false);
}

export function ResponseNewZoneApiZoneNewPostToJSONTyped(value?: ResponseNewZoneApiZoneNewPost | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

