/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScenarioPhotovoltaicType } from './ScenarioPhotovoltaicType';
import {
    ScenarioPhotovoltaicTypeFromJSON,
    ScenarioPhotovoltaicTypeFromJSONTyped,
    ScenarioPhotovoltaicTypeToJSON,
    ScenarioPhotovoltaicTypeToJSONTyped,
} from './ScenarioPhotovoltaicType';

/**
 * 
 * @export
 * @interface Scenario
 */
export interface Scenario {
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Scenario
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    climate_scenario_id: number;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    archived?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    visible?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    calibration?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    future?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    renovation_wall?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    renovation_windows?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    renovation_roof?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    renovation_floor?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    renovation_heat_pump?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    renovation_start?: number;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    renovation_rate?: number;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    renovation_min?: number;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    renovation_max?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    full_renovation_wall?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    full_renovation_windows?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    full_renovation_roof?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    full_renovation_floor?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    full_renovation_heat_pump?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    full_renovation_start?: number;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    full_renovation_rate?: number;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    full_renovation_min?: number;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    full_renovation_max?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Scenario
     */
    photovoltaic_installation: boolean;
    /**
     * 
     * @type {ScenarioPhotovoltaicType}
     * @memberof Scenario
     */
    photovoltaic_type?: ScenarioPhotovoltaicType;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    photovoltaic_installation_start?: number;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    photovoltaic_installation_rate?: number;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    photovoltaic_installation_min?: number;
    /**
     * 
     * @type {number}
     * @memberof Scenario
     */
    photovoltaic_installation_max?: number;
}



/**
 * Check if a given object implements the Scenario interface.
 */
export function instanceOfScenario(value: object): value is Scenario {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('climate_scenario_id' in value) || value['climate_scenario_id'] === undefined) return false;
    if (!('photovoltaic_installation' in value) || value['photovoltaic_installation'] === undefined) return false;
    return true;
}

export function ScenarioFromJSON(json: any): Scenario {
    return ScenarioFromJSONTyped(json, false);
}

export function ScenarioFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scenario {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'climate_scenario_id': json['climate_scenario_id'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'visible': json['visible'] == null ? undefined : json['visible'],
        'calibration': json['calibration'] == null ? undefined : json['calibration'],
        'future': json['future'] == null ? undefined : json['future'],
        'renovation_wall': json['renovation_wall'] == null ? undefined : json['renovation_wall'],
        'renovation_windows': json['renovation_windows'] == null ? undefined : json['renovation_windows'],
        'renovation_roof': json['renovation_roof'] == null ? undefined : json['renovation_roof'],
        'renovation_floor': json['renovation_floor'] == null ? undefined : json['renovation_floor'],
        'renovation_heat_pump': json['renovation_heat_pump'] == null ? undefined : json['renovation_heat_pump'],
        'renovation_start': json['renovation_start'] == null ? undefined : json['renovation_start'],
        'renovation_rate': json['renovation_rate'] == null ? undefined : json['renovation_rate'],
        'renovation_min': json['renovation_min'] == null ? undefined : json['renovation_min'],
        'renovation_max': json['renovation_max'] == null ? undefined : json['renovation_max'],
        'full_renovation_wall': json['full_renovation_wall'] == null ? undefined : json['full_renovation_wall'],
        'full_renovation_windows': json['full_renovation_windows'] == null ? undefined : json['full_renovation_windows'],
        'full_renovation_roof': json['full_renovation_roof'] == null ? undefined : json['full_renovation_roof'],
        'full_renovation_floor': json['full_renovation_floor'] == null ? undefined : json['full_renovation_floor'],
        'full_renovation_heat_pump': json['full_renovation_heat_pump'] == null ? undefined : json['full_renovation_heat_pump'],
        'full_renovation_start': json['full_renovation_start'] == null ? undefined : json['full_renovation_start'],
        'full_renovation_rate': json['full_renovation_rate'] == null ? undefined : json['full_renovation_rate'],
        'full_renovation_min': json['full_renovation_min'] == null ? undefined : json['full_renovation_min'],
        'full_renovation_max': json['full_renovation_max'] == null ? undefined : json['full_renovation_max'],
        'photovoltaic_installation': json['photovoltaic_installation'],
        'photovoltaic_type': json['photovoltaic_type'] == null ? undefined : ScenarioPhotovoltaicTypeFromJSON(json['photovoltaic_type']),
        'photovoltaic_installation_start': json['photovoltaic_installation_start'] == null ? undefined : json['photovoltaic_installation_start'],
        'photovoltaic_installation_rate': json['photovoltaic_installation_rate'] == null ? undefined : json['photovoltaic_installation_rate'],
        'photovoltaic_installation_min': json['photovoltaic_installation_min'] == null ? undefined : json['photovoltaic_installation_min'],
        'photovoltaic_installation_max': json['photovoltaic_installation_max'] == null ? undefined : json['photovoltaic_installation_max'],
    };
}

export function ScenarioToJSON(json: any): Scenario {
    return ScenarioToJSONTyped(json, false);
}

export function ScenarioToJSONTyped(value?: Scenario | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'climate_scenario_id': value['climate_scenario_id'],
        'archived': value['archived'],
        'visible': value['visible'],
        'calibration': value['calibration'],
        'future': value['future'],
        'renovation_wall': value['renovation_wall'],
        'renovation_windows': value['renovation_windows'],
        'renovation_roof': value['renovation_roof'],
        'renovation_floor': value['renovation_floor'],
        'renovation_heat_pump': value['renovation_heat_pump'],
        'renovation_start': value['renovation_start'],
        'renovation_rate': value['renovation_rate'],
        'renovation_min': value['renovation_min'],
        'renovation_max': value['renovation_max'],
        'full_renovation_wall': value['full_renovation_wall'],
        'full_renovation_windows': value['full_renovation_windows'],
        'full_renovation_roof': value['full_renovation_roof'],
        'full_renovation_floor': value['full_renovation_floor'],
        'full_renovation_heat_pump': value['full_renovation_heat_pump'],
        'full_renovation_start': value['full_renovation_start'],
        'full_renovation_rate': value['full_renovation_rate'],
        'full_renovation_min': value['full_renovation_min'],
        'full_renovation_max': value['full_renovation_max'],
        'photovoltaic_installation': value['photovoltaic_installation'],
        'photovoltaic_type': ScenarioPhotovoltaicTypeToJSON(value['photovoltaic_type']),
        'photovoltaic_installation_start': value['photovoltaic_installation_start'],
        'photovoltaic_installation_rate': value['photovoltaic_installation_rate'],
        'photovoltaic_installation_min': value['photovoltaic_installation_min'],
        'photovoltaic_installation_max': value['photovoltaic_installation_max'],
    };
}

