/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ScenarioPhotovoltaicType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type ScenarioPhotovoltaicType = typeof ScenarioPhotovoltaicType[keyof typeof ScenarioPhotovoltaicType];


export function instanceOfScenarioPhotovoltaicType(value: any): boolean {
    for (const key in ScenarioPhotovoltaicType) {
        if (Object.prototype.hasOwnProperty.call(ScenarioPhotovoltaicType, key)) {
            if (ScenarioPhotovoltaicType[key as keyof typeof ScenarioPhotovoltaicType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ScenarioPhotovoltaicTypeFromJSON(json: any): ScenarioPhotovoltaicType {
    return ScenarioPhotovoltaicTypeFromJSONTyped(json, false);
}

export function ScenarioPhotovoltaicTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScenarioPhotovoltaicType {
    return json as ScenarioPhotovoltaicType;
}

export function ScenarioPhotovoltaicTypeToJSON(value?: ScenarioPhotovoltaicType | null): any {
    return value as any;
}

export function ScenarioPhotovoltaicTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ScenarioPhotovoltaicType {
    return value as ScenarioPhotovoltaicType;
}

