/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulationInfo
 */
export interface SimulationInfo {
    /**
     * 
     * @type {number}
     * @memberof SimulationInfo
     */
    simulation_id: number;
    /**
     * 
     * @type {number}
     * @memberof SimulationInfo
     */
    scenario_id: number;
    /**
     * 
     * @type {number}
     * @memberof SimulationInfo
     */
    climate_scenario_id: number;
    /**
     * 
     * @type {number}
     * @memberof SimulationInfo
     */
    climate_id: number;
    /**
     * 
     * @type {number}
     * @memberof SimulationInfo
     */
    year: number;
}

/**
 * Check if a given object implements the SimulationInfo interface.
 */
export function instanceOfSimulationInfo(value: object): value is SimulationInfo {
    if (!('simulation_id' in value) || value['simulation_id'] === undefined) return false;
    if (!('scenario_id' in value) || value['scenario_id'] === undefined) return false;
    if (!('climate_scenario_id' in value) || value['climate_scenario_id'] === undefined) return false;
    if (!('climate_id' in value) || value['climate_id'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    return true;
}

export function SimulationInfoFromJSON(json: any): SimulationInfo {
    return SimulationInfoFromJSONTyped(json, false);
}

export function SimulationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulationInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'simulation_id': json['simulation_id'],
        'scenario_id': json['scenario_id'],
        'climate_scenario_id': json['climate_scenario_id'],
        'climate_id': json['climate_id'],
        'year': json['year'],
    };
}

export function SimulationInfoToJSON(json: any): SimulationInfo {
    return SimulationInfoToJSONTyped(json, false);
}

export function SimulationInfoToJSONTyped(value?: SimulationInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simulation_id': value['simulation_id'],
        'scenario_id': value['scenario_id'],
        'climate_scenario_id': value['climate_scenario_id'],
        'climate_id': value['climate_id'],
        'year': value['year'],
    };
}

