/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimulationStatus } from './SimulationStatus';
import {
    SimulationStatusFromJSON,
    SimulationStatusFromJSONTyped,
    SimulationStatusToJSON,
    SimulationStatusToJSONTyped,
} from './SimulationStatus';

/**
 * 
 * @export
 * @interface Simulation
 */
export interface Simulation {
    /**
     * 
     * @type {number}
     * @memberof Simulation
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Simulation
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Simulation
     */
    year?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Simulation
     */
    scenario_id: number;
    /**
     * 
     * @type {number}
     * @memberof Simulation
     */
    climate_id: number;
    /**
     * 
     * @type {number}
     * @memberof Simulation
     */
    zone_id: number;
    /**
     * 
     * @type {string}
     * @memberof Simulation
     */
    horizon_file: string;
    /**
     * 
     * @type {SimulationStatus}
     * @memberof Simulation
     */
    status?: SimulationStatus;
}



/**
 * Check if a given object implements the Simulation interface.
 */
export function instanceOfSimulation(value: object): value is Simulation {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scenario_id' in value) || value['scenario_id'] === undefined) return false;
    if (!('climate_id' in value) || value['climate_id'] === undefined) return false;
    if (!('zone_id' in value) || value['zone_id'] === undefined) return false;
    if (!('horizon_file' in value) || value['horizon_file'] === undefined) return false;
    return true;
}

export function SimulationFromJSON(json: any): Simulation {
    return SimulationFromJSONTyped(json, false);
}

export function SimulationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Simulation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'year': json['year'] == null ? undefined : json['year'],
        'scenario_id': json['scenario_id'],
        'climate_id': json['climate_id'],
        'zone_id': json['zone_id'],
        'horizon_file': json['horizon_file'],
        'status': json['status'] == null ? undefined : SimulationStatusFromJSON(json['status']),
    };
}

export function SimulationToJSON(json: any): Simulation {
    return SimulationToJSONTyped(json, false);
}

export function SimulationToJSONTyped(value?: Simulation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'year': value['year'],
        'scenario_id': value['scenario_id'],
        'climate_id': value['climate_id'],
        'zone_id': value['zone_id'],
        'horizon_file': value['horizon_file'],
        'status': SimulationStatusToJSON(value['status']),
    };
}

