/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SimulationStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8
} as const;
export type SimulationStatus = typeof SimulationStatus[keyof typeof SimulationStatus];


export function instanceOfSimulationStatus(value: any): boolean {
    for (const key in SimulationStatus) {
        if (Object.prototype.hasOwnProperty.call(SimulationStatus, key)) {
            if (SimulationStatus[key as keyof typeof SimulationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SimulationStatusFromJSON(json: any): SimulationStatus {
    return SimulationStatusFromJSONTyped(json, false);
}

export function SimulationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulationStatus {
    return json as SimulationStatus;
}

export function SimulationStatusToJSON(value?: SimulationStatus | null): any {
    return value as any;
}

export function SimulationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): SimulationStatus {
    return value as SimulationStatus;
}

