/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultiPolygon } from './MultiPolygon';
import {
    MultiPolygonFromJSON,
    MultiPolygonFromJSONTyped,
    MultiPolygonToJSON,
    MultiPolygonToJSONTyped,
} from './MultiPolygon';
import type { SolidType } from './SolidType';
import {
    SolidTypeFromJSON,
    SolidTypeFromJSONTyped,
    SolidTypeToJSON,
    SolidTypeToJSONTyped,
} from './SolidType';

/**
 * 
 * @export
 * @interface Solid
 */
export interface Solid {
    /**
     * 
     * @type {number}
     * @memberof Solid
     */
    id?: number | null;
    /**
     * 
     * @type {SolidType}
     * @memberof Solid
     */
    solid_type?: SolidType;
    /**
     * 
     * @type {MultiPolygon}
     * @memberof Solid
     */
    data: MultiPolygon;
    /**
     * 
     * @type {number}
     * @memberof Solid
     */
    asset_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Solid
     */
    layer_id: number;
    /**
     * 
     * @type {number}
     * @memberof Solid
     */
    extent_id: number;
    /**
     * 
     * @type {number}
     * @memberof Solid
     */
    object_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Solid
     */
    parent_id?: number | null;
}



/**
 * Check if a given object implements the Solid interface.
 */
export function instanceOfSolid(value: object): value is Solid {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('asset_id' in value) || value['asset_id'] === undefined) return false;
    if (!('layer_id' in value) || value['layer_id'] === undefined) return false;
    if (!('extent_id' in value) || value['extent_id'] === undefined) return false;
    return true;
}

export function SolidFromJSON(json: any): Solid {
    return SolidFromJSONTyped(json, false);
}

export function SolidFromJSONTyped(json: any, ignoreDiscriminator: boolean): Solid {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'solid_type': json['solid_type'] == null ? undefined : SolidTypeFromJSON(json['solid_type']),
        'data': MultiPolygonFromJSON(json['data']),
        'asset_id': json['asset_id'],
        'layer_id': json['layer_id'],
        'extent_id': json['extent_id'],
        'object_id': json['object_id'] == null ? undefined : json['object_id'],
        'parent_id': json['parent_id'] == null ? undefined : json['parent_id'],
    };
}

export function SolidToJSON(json: any): Solid {
    return SolidToJSONTyped(json, false);
}

export function SolidToJSONTyped(value?: Solid | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'solid_type': SolidTypeToJSON(value['solid_type']),
        'data': MultiPolygonToJSON(value['data']),
        'asset_id': value['asset_id'],
        'layer_id': value['layer_id'],
        'extent_id': value['extent_id'],
        'object_id': value['object_id'],
        'parent_id': value['parent_id'],
    };
}

