/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SolidType = {
    NUMBER_0: 0
} as const;
export type SolidType = typeof SolidType[keyof typeof SolidType];


export function instanceOfSolidType(value: any): boolean {
    for (const key in SolidType) {
        if (Object.prototype.hasOwnProperty.call(SolidType, key)) {
            if (SolidType[key as keyof typeof SolidType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SolidTypeFromJSON(json: any): SolidType {
    return SolidTypeFromJSONTyped(json, false);
}

export function SolidTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolidType {
    return json as SolidType;
}

export function SolidTypeToJSON(value?: SolidType | null): any {
    return value as any;
}

export function SolidTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SolidType {
    return value as SolidType;
}

