/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SurfaceType = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type SurfaceType = typeof SurfaceType[keyof typeof SurfaceType];


export function instanceOfSurfaceType(value: any): boolean {
    for (const key in SurfaceType) {
        if (Object.prototype.hasOwnProperty.call(SurfaceType, key)) {
            if (SurfaceType[key as keyof typeof SurfaceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SurfaceTypeFromJSON(json: any): SurfaceType {
    return SurfaceTypeFromJSONTyped(json, false);
}

export function SurfaceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SurfaceType {
    return json as SurfaceType;
}

export function SurfaceTypeToJSON(value?: SurfaceType | null): any {
    return value as any;
}

export function SurfaceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SurfaceType {
    return value as SurfaceType;
}

