/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultiPolygon } from './MultiPolygon';
import {
    MultiPolygonFromJSON,
    MultiPolygonFromJSONTyped,
    MultiPolygonToJSON,
    MultiPolygonToJSONTyped,
} from './MultiPolygon';
import type { SurfaceType } from './SurfaceType';
import {
    SurfaceTypeFromJSON,
    SurfaceTypeFromJSONTyped,
    SurfaceTypeToJSON,
    SurfaceTypeToJSONTyped,
} from './SurfaceType';

/**
 * 
 * @export
 * @interface Surface
 */
export interface Surface {
    /**
     * 
     * @type {number}
     * @memberof Surface
     */
    id?: number | null;
    /**
     * 
     * @type {SurfaceType}
     * @memberof Surface
     */
    surface_type?: SurfaceType;
    /**
     * 
     * @type {MultiPolygon}
     * @memberof Surface
     */
    data: MultiPolygon;
    /**
     * 
     * @type {MultiPolygon}
     * @memberof Surface
     */
    collection: MultiPolygon;
    /**
     * 
     * @type {number}
     * @memberof Surface
     */
    asset_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof Surface
     */
    layer_id: number;
    /**
     * 
     * @type {number}
     * @memberof Surface
     */
    zone_id: number;
    /**
     * 
     * @type {number}
     * @memberof Surface
     */
    extent_id: number;
    /**
     * 
     * @type {number}
     * @memberof Surface
     */
    object_id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Surface
     */
    parent_id?: number | null;
}



/**
 * Check if a given object implements the Surface interface.
 */
export function instanceOfSurface(value: object): value is Surface {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('collection' in value) || value['collection'] === undefined) return false;
    if (!('asset_id' in value) || value['asset_id'] === undefined) return false;
    if (!('layer_id' in value) || value['layer_id'] === undefined) return false;
    if (!('zone_id' in value) || value['zone_id'] === undefined) return false;
    if (!('extent_id' in value) || value['extent_id'] === undefined) return false;
    return true;
}

export function SurfaceFromJSON(json: any): Surface {
    return SurfaceFromJSONTyped(json, false);
}

export function SurfaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Surface {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'surface_type': json['surface_type'] == null ? undefined : SurfaceTypeFromJSON(json['surface_type']),
        'data': MultiPolygonFromJSON(json['data']),
        'collection': MultiPolygonFromJSON(json['collection']),
        'asset_id': json['asset_id'],
        'layer_id': json['layer_id'],
        'zone_id': json['zone_id'],
        'extent_id': json['extent_id'],
        'object_id': json['object_id'] == null ? undefined : json['object_id'],
        'parent_id': json['parent_id'] == null ? undefined : json['parent_id'],
    };
}

export function SurfaceToJSON(json: any): Surface {
    return SurfaceToJSONTyped(json, false);
}

export function SurfaceToJSONTyped(value?: Surface | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'surface_type': SurfaceTypeToJSON(value['surface_type']),
        'data': MultiPolygonToJSON(value['data']),
        'collection': MultiPolygonToJSON(value['collection']),
        'asset_id': value['asset_id'],
        'layer_id': value['layer_id'],
        'zone_id': value['zone_id'],
        'extent_id': value['extent_id'],
        'object_id': value['object_id'],
        'parent_id': value['parent_id'],
    };
}

