/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextureObject
 */
export interface TextureObject {
    /**
     * 
     * @type {string}
     * @memberof TextureObject
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof TextureObject
     */
    image?: string;
}

/**
 * Check if a given object implements the TextureObject interface.
 */
export function instanceOfTextureObject(value: object): value is TextureObject {
    return true;
}

export function TextureObjectFromJSON(json: any): TextureObject {
    return TextureObjectFromJSONTyped(json, false);
}

export function TextureObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextureObject {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function TextureObjectToJSON(json: any): TextureObject {
    return TextureObjectToJSONTyped(json, false);
}

export function TextureObjectToJSONTyped(value?: TextureObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'image': value['image'],
    };
}

