/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSeriesInfo
 */
export interface TimeSeriesInfo {
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesInfo
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesInfo
     */
    scenario_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesInfo
     */
    simulation_id: number | null;
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesInfo
     */
    unit: string;
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesInfo
     */
    num_values: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesInfo
     */
    value_min: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesInfo
     */
    value_max: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesInfo
     */
    value_avg: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesInfo
     */
    value_sum: number;
    /**
     * 
     * @type {Date}
     * @memberof TimeSeriesInfo
     */
    time_start: Date;
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesInfo
     */
    time_delta: string;
}

/**
 * Check if a given object implements the TimeSeriesInfo interface.
 */
export function instanceOfTimeSeriesInfo(value: object): value is TimeSeriesInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('scenario_id' in value) || value['scenario_id'] === undefined) return false;
    if (!('simulation_id' in value) || value['simulation_id'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('num_values' in value) || value['num_values'] === undefined) return false;
    if (!('value_min' in value) || value['value_min'] === undefined) return false;
    if (!('value_max' in value) || value['value_max'] === undefined) return false;
    if (!('value_avg' in value) || value['value_avg'] === undefined) return false;
    if (!('value_sum' in value) || value['value_sum'] === undefined) return false;
    if (!('time_start' in value) || value['time_start'] === undefined) return false;
    if (!('time_delta' in value) || value['time_delta'] === undefined) return false;
    return true;
}

export function TimeSeriesInfoFromJSON(json: any): TimeSeriesInfo {
    return TimeSeriesInfoFromJSONTyped(json, false);
}

export function TimeSeriesInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSeriesInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'scenario_id': json['scenario_id'],
        'simulation_id': json['simulation_id'],
        'unit': json['unit'],
        'num_values': json['num_values'],
        'value_min': json['value_min'],
        'value_max': json['value_max'],
        'value_avg': json['value_avg'],
        'value_sum': json['value_sum'],
        'time_start': (new Date(json['time_start'])),
        'time_delta': json['time_delta'],
    };
}

export function TimeSeriesInfoToJSON(json: any): TimeSeriesInfo {
    return TimeSeriesInfoToJSONTyped(json, false);
}

export function TimeSeriesInfoToJSONTyped(value?: TimeSeriesInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'scenario_id': value['scenario_id'],
        'simulation_id': value['simulation_id'],
        'unit': value['unit'],
        'num_values': value['num_values'],
        'value_min': value['value_min'],
        'value_max': value['value_max'],
        'value_avg': value['value_avg'],
        'value_sum': value['value_sum'],
        'time_start': ((value['time_start']).toISOString()),
        'time_delta': value['time_delta'],
    };
}

