/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSeries
 */
export interface TimeSeries {
    /**
     * 
     * @type {number}
     * @memberof TimeSeries
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TimeSeries
     */
    time_series_type_id: number;
    /**
     * 
     * @type {Array<any>}
     * @memberof TimeSeries
     */
    data?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof TimeSeries
     */
    timestamp?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof TimeSeries
     */
    asset_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof TimeSeries
     */
    layer_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof TimeSeries
     */
    object_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof TimeSeries
     */
    interval_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof TimeSeries
     */
    climate_scenario_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof TimeSeries
     */
    scenario_id: number | null;
    /**
     * 
     * @type {number}
     * @memberof TimeSeries
     */
    simulation_id: number | null;
}

/**
 * Check if a given object implements the TimeSeries interface.
 */
export function instanceOfTimeSeries(value: object): value is TimeSeries {
    if (!('time_series_type_id' in value) || value['time_series_type_id'] === undefined) return false;
    if (!('asset_id' in value) || value['asset_id'] === undefined) return false;
    if (!('layer_id' in value) || value['layer_id'] === undefined) return false;
    if (!('object_id' in value) || value['object_id'] === undefined) return false;
    if (!('interval_id' in value) || value['interval_id'] === undefined) return false;
    if (!('climate_scenario_id' in value) || value['climate_scenario_id'] === undefined) return false;
    if (!('scenario_id' in value) || value['scenario_id'] === undefined) return false;
    if (!('simulation_id' in value) || value['simulation_id'] === undefined) return false;
    return true;
}

export function TimeSeriesFromJSON(json: any): TimeSeries {
    return TimeSeriesFromJSONTyped(json, false);
}

export function TimeSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSeries {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'time_series_type_id': json['time_series_type_id'],
        'data': json['data'] == null ? undefined : json['data'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'asset_id': json['asset_id'],
        'layer_id': json['layer_id'],
        'object_id': json['object_id'],
        'interval_id': json['interval_id'],
        'climate_scenario_id': json['climate_scenario_id'],
        'scenario_id': json['scenario_id'],
        'simulation_id': json['simulation_id'],
    };
}

export function TimeSeriesToJSON(json: any): TimeSeries {
    return TimeSeriesToJSONTyped(json, false);
}

export function TimeSeriesToJSONTyped(value?: TimeSeries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'time_series_type_id': value['time_series_type_id'],
        'data': value['data'],
        'timestamp': value['timestamp'],
        'asset_id': value['asset_id'],
        'layer_id': value['layer_id'],
        'object_id': value['object_id'],
        'interval_id': value['interval_id'],
        'climate_scenario_id': value['climate_scenario_id'],
        'scenario_id': value['scenario_id'],
        'simulation_id': value['simulation_id'],
    };
}

