/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSeriesType
 */
export interface TimeSeriesType {
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesType
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesType
     */
    alias: string;
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesType
     */
    unit_id: number | null;
}

/**
 * Check if a given object implements the TimeSeriesType interface.
 */
export function instanceOfTimeSeriesType(value: object): value is TimeSeriesType {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('unit_id' in value) || value['unit_id'] === undefined) return false;
    return true;
}

export function TimeSeriesTypeFromJSON(json: any): TimeSeriesType {
    return TimeSeriesTypeFromJSONTyped(json, false);
}

export function TimeSeriesTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSeriesType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'alias': json['alias'],
        'unit_id': json['unit_id'],
    };
}

export function TimeSeriesTypeToJSON(json: any): TimeSeriesType {
    return TimeSeriesTypeToJSONTyped(json, false);
}

export function TimeSeriesTypeToJSONTyped(value?: TimeSeriesType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'alias': value['alias'],
        'unit_id': value['unit_id'],
    };
}

