/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ZoneStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9
} as const;
export type ZoneStatus = typeof ZoneStatus[keyof typeof ZoneStatus];


export function instanceOfZoneStatus(value: any): boolean {
    for (const key in ZoneStatus) {
        if (Object.prototype.hasOwnProperty.call(ZoneStatus, key)) {
            if (ZoneStatus[key as keyof typeof ZoneStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ZoneStatusFromJSON(json: any): ZoneStatus {
    return ZoneStatusFromJSONTyped(json, false);
}

export function ZoneStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZoneStatus {
    return json as ZoneStatus;
}

export function ZoneStatusToJSON(value?: ZoneStatus | null): any {
    return value as any;
}

export function ZoneStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ZoneStatus {
    return value as ZoneStatus;
}

