/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ZoneType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7
} as const;
export type ZoneType = typeof ZoneType[keyof typeof ZoneType];


export function instanceOfZoneType(value: any): boolean {
    for (const key in ZoneType) {
        if (Object.prototype.hasOwnProperty.call(ZoneType, key)) {
            if (ZoneType[key as keyof typeof ZoneType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ZoneTypeFromJSON(json: any): ZoneType {
    return ZoneTypeFromJSONTyped(json, false);
}

export function ZoneTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZoneType {
    return json as ZoneType;
}

export function ZoneTypeToJSON(value?: ZoneType | null): any {
    return value as any;
}

export function ZoneTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ZoneType {
    return value as ZoneType;
}

