/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ZoneStatus } from './ZoneStatus';
import {
    ZoneStatusFromJSON,
    ZoneStatusFromJSONTyped,
    ZoneStatusToJSON,
    ZoneStatusToJSONTyped,
} from './ZoneStatus';
import type { ZoneType } from './ZoneType';
import {
    ZoneTypeFromJSON,
    ZoneTypeFromJSONTyped,
    ZoneTypeToJSON,
    ZoneTypeToJSONTyped,
} from './ZoneType';

/**
 * 
 * @export
 * @interface Zone
 */
export interface Zone {
    /**
     * 
     * @type {number}
     * @memberof Zone
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Zone
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Zone
     */
    extent_id: number;
    /**
     * 
     * @type {number}
     * @memberof Zone
     */
    parent_id?: number | null;
    /**
     * 
     * @type {ZoneType}
     * @memberof Zone
     */
    type?: ZoneType;
    /**
     * 
     * @type {ZoneStatus}
     * @memberof Zone
     */
    status?: ZoneStatus;
}



/**
 * Check if a given object implements the Zone interface.
 */
export function instanceOfZone(value: object): value is Zone {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('extent_id' in value) || value['extent_id'] === undefined) return false;
    return true;
}

export function ZoneFromJSON(json: any): Zone {
    return ZoneFromJSONTyped(json, false);
}

export function ZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): Zone {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'extent_id': json['extent_id'],
        'parent_id': json['parent_id'] == null ? undefined : json['parent_id'],
        'type': json['type'] == null ? undefined : ZoneTypeFromJSON(json['type']),
        'status': json['status'] == null ? undefined : ZoneStatusFromJSON(json['status']),
    };
}

export function ZoneToJSON(json: any): Zone {
    return ZoneToJSONTyped(json, false);
}

export function ZoneToJSONTyped(value?: Zone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'extent_id': value['extent_id'],
        'parent_id': value['parent_id'],
        'type': ZoneTypeToJSON(value['type']),
        'status': ZoneStatusToJSON(value['status']),
    };
}

